### ISSUE TITLE
Decklist missing duplicates

### ISSUE THREAD

**Issue by HowIsYourMoM** [Epix37/Hearthstone-Deck-Tracker#1006]
Hello,i created a new deck and my duplicated cards arent shown,only one,someones shows me correctly,others dont.Also the game goes really slow sometimes,is due to the HS tracker?

How to fix it.

**Comment by Epix37** [comment]
Not realy sure what the problem is. Try creating the deck from scratch again. 

HDT *may* cause your game to run slow, yes. Most likely one of two reasons:
1) Try turning windows aero on/off. (Or try turning the overlay off in the options)
2) Your harddrive might be too slow  to handle all the data logged by Hearthstone. To test this, run "HDTUninstaller" and remove the Hearthstone logging. Restart Hearthstone. **Running HDT again will re-enable the logging**

**Comment by jleclanche** [comment]
Closing due to lack of feedback.
