### ISSUE TITLE
Gnomish Experimenter seems to screw with all aspects of the tracking system

### ISSUE THREAD

**Issue by rrwoods** [Epix37/Hearthstone-Deck-Tracker#1038]
When I play a Gnomish Experimenter and draw a minion, the minion is still highlighted in my decklist (even though it turned into a chicken).

When my opponent plays Gnomish Experimenter, strange things happen -- the marks over their hand indicated they had more cards than they actually did.  Some cards were marked green in their decklist and I'm not sure why; one of them was Flamestrike (maybe it was the card they drew from the first Experimenter?) and the other was Harvest Golem (I've got no clue on that one).

**Comment by mvordeme** [comment]
Something similar happened to me yesterday. I wasn't sure it was caused by the Experimenter, but it seems my guess was right. After my opponent played the Experimenter, HDT constantly showed one more card in the opponent's hand than Hearthstone itself. Maybe HDT can't handle the fact that a certain minion is drawn but an entirely different minion is added to the hand.

**Comment by riQQ** [comment]
Playing Gnomish Experimenter works correctly for me now.
Haven't checked Gnomish Experimenter being played by the opponent yet.

**Comment by Epix37** [comment]
Probably fixed. Let me know if it's sitll an issue.
