### ISSUE TITLE
(Faster?) Error detection for hearthstats syncing

### ISSUE THREAD

**Issue by dantedog** [Epix37/Hearthstone-Deck-Tracker#1041]
I'll admit, I just force quit deck tracker after ~5 minutes, So it may time out eventually. It seems that if the hearthstats server is down, deck tracker will continue trying to sync until it comes back up. It looks like hdt knows the heartstats server is down (the little red exclamation mark), but the syncing function appears to hang anyways. Maybe just a cancel button on the [syncing](http://i.imgur.com/mRM3ygP.png) screen in the worst case scenario.

**Comment by HDANILO** [comment]
The best solution to keep syncing but not stress out the computer/resources is to double sync_wait time for every try up to a maximum!

For example:

Trying to sync: server down.
wait 4s
Trying to sync: server down.
wait 8s
Trying to sync: server down.
wait 16s
Trying to sync: server down;
wait 32s
Trying to sync: server down;
wait 62s
Trying to sync: server down;
....
wait 30min
Trying to sync: server down;
wait 30min

Its this way that android implements sync tasks and its good because it does not consume too much resource, not as many as try again every 1 min.

I'm not in the develop team but I guess this sugestion could be good for them
