### ISSUE TITLE
Export in HearthStone miss first card

### ISSUE THREAD

**Issue by Zaytchik** [Epix37/Hearthstone-Deck-Tracker#1106]
I tried to export 2 decks to Hearthstone and both times, first card was missed exported -->

Hunt, it selected (in game) 2 x hunter's mark instead of 2 x Webspinner, 

Mage, it selected (in game) 2 x Mirror Image instead of 2 x Mana Wyrm.

Both time, after entering deck's name, i had a red message (in game) "you must select a friend before starting a chat" (like when you press "enter" with no active chat with any contact)..

Good luck ;)

**Comment by garralab** [comment]
More on this, I've got the same problem and from what I see after the message reported by Zaytchik the clicks the searchbox but the searchbox is still empty. Probably the game client changed behaviour of Enter pressed while building a deck in the last release.

**Comment by andburn** [comment]
Same problem as #1091 and related to #1094. It's due to the new layout of the collection manager, the button that filters cards by set specifically. Basically, the first card search is now being blocked, making the first card in a deck be the first card in that hero's list (or the second one if you have gold prioritized).

Anyway, I've submitted a fix for it.

**Comment by feliperautacabral** [comment]
How do I fix that? I am COMPLETELY  unfamiliar to any sort of programming and have no idea to do this =]

**Comment by andburn** [comment]
Sorry, I didn't mean that you could apply the fix yourself. 
I meant I've submitted some code that will fix the problem, but it has to be approved and added to the code base. Then it should be available in the next update.

**Comment by Epix37** [comment]
See #1111.
