### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by TheIndigoWendigo** [Epix37/Hearthstone-Deck-Tracker#1117]
So after using it I noticed some performance issues and decided to uninstall the deck tracker but I am still having performance issues. Before installing hearthstone ran perfectly.I have even uninstalled and reinstalled hearthstone. I really want to know how to fix this since my playing experience hasn't been very fun with the lag spikes every action.

**Comment by culinko** [comment]
Many other people are experiencing similar issues, see #1097.
To fix it, you need to disable logging: #889#issuecomment-91897307 (but then you won't be able to run Deck Tracker at all).

**Comment by TheIndigoWendigo** [comment]
Thank you so much. It's really strange that my computer isn't able to handle this and I'm rather sad about it. I'm  happy though that now I have a smooth running game.

**Comment by chaosjockey** [comment]
I'm having performance issues with HDT as well.
While the HDT is running I experience computer-wide performance issues, everything from explorer not responding to cursor lag.
The moment I completely close HDT everything returns to normal. I can create a new issue if need be but I thought instead of creating another issue about performance i'd respond here.

**Comment by culinko** [comment]
I believe there are 2 similar issues. See my last post in #1133.

**Comment by chaosjockey** [comment]
I will give that a shot. Thank you!

**Comment by culinko** [comment]
Unfortunately, there is nothing you can do to fix it, because Deck Tracker needs the logging enabled. I was just pointing out about 2 different issues people are having. One is that once you close Deck Tracker, game is running smoothly (your issue) and the other one is that even if you close Deck Tracker, the game is still choppy and you need to disable logging as well to fix it.
