### ISSUE TITLE
FPS Droped.

### ISSUE THREAD

**Issue by sirerie** [Epix37/Hearthstone-Deck-Tracker#1133]
whenever i play hearthstone trying this ttracking my games skips frames even when i dont use the deck tracker.

**Comment by culinko** [comment]
#1097.

**Comment by caldwelljt2** [comment]
I've been using hearthstone deck tracker for quite a while and I can second this issue. Somehow during the last couple updates, deck tracker has slowed my FPS down so much that i'm actually unable to reliably move my mouse around and perform standard moves in hearthstone.

I suspect hearthstone tracker because when I close it and play, my FPS returns to normal. It affects both the game and the mouse curser, and I've had several games where I just couldn't move the mouse enough to finish in time, which is more frustrating than going without hearthstone tracker.

I haven't made any changes to my setup, so I don't really know how to troubleshoot it. It seems to come and go at random so long as hearthstone tracker is running in the background.

**Comment by andburn** [comment]
As @culinko has pointed out there is a already an issue about this "[Hearthstone suddenly choppy after installing](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1097)". It seems to effect only some people, no solution so far unfortunately.

**Comment by culinko** [comment]
But this sounds like a different problem, because his FPS return to normal once he closes Deck Tracker. So he still has logging enabled, which causes the FPS drops for other people.

**Comment by andburn** [comment]
Whoops, you're right @culinko I didn't read it properly!

**Comment by culinko** [comment]
So the problem in the initial post have already been fixed, but the other guy had a different problem. Not sure what to do with this ticket now.

**Comment by Cu8eR** [comment]
@culinko @Epix37 

This is fixed right? At least when you disable interactivity this issue disappears
