### ISSUE TITLE
Can't get stats from deck.

### ISSUE THREAD

**Issue by MrSmash** [Epix37/Hearthstone-Deck-Tracker#1188]
This is my first time downloading a program like this, I'm not sure if it's just my personal error or a bug but I cannot seem to get stats or getting the "Hand: X Deck: X" feature to work either. Any suggestions?

**Comment by andburn** [comment]
It is probably because you haven't set a deck to be active, see the [FAQ](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#active-deck) for more info. 
There also seems to be a bug at the moment that means you have to have to make some deck active before the auto-selection function kicks in.
Let us know how you get on.
