### ISSUE TITLE
Tavern brawl errors and suggestion

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#1190]
When playing games in tavern brawl, they are being saved as Mage regardless of the class.
I cant move them to a deck of the right class because in Move To Other Deck, only mage decks are presented as options.

It also shows opponent deck as Mage, regardless of what they actually were.

Also: HDT needs a new mode, Tavern Brawl. So stats are recorded correctly, and also so you can create decks for them properly.

**Comment by andburn** [comment]
I hadn't noticed the deck's being saved as Mage, it must be only this week due to the *Unstable Portals*. It must've happened with Hunter and the *Webspinners* too. I'll see if it can be fixed easily.

I've added some fixes for Brawl including the game mode (#1178), won't be available until @Epix37 releases an update though.

Also, as I said over on #1149, I'm not sure a Brawl deck type is necessary. So far, the deck building follows the same rules as constructed. I think adding a "Tavern Brawl" tag to constructed decks is a decent solution. Would you really want to save the pre-made decks, like this week ones?

**Comment by GiggliG** [comment]
Thanks for the work you are doing. I've seen you in other threads doing a lot of good stuff. 

About your question: I wouldn't want to save this week's decks, but the brawls alternate between prebuilt/random and 'constructed'. The constructed brawls have the potential to break the normal rules of constructed. It's likely that sooner or later we'll see deckbuilding that allows you to pick more than 2 copies of a card, and HDT doesn't allow you do do that with the constructed deck type.

HDT's Arena decks allow any number of cards, so i guess the ideal for me would be for the Arena decktype could be changed to display as Arena/Brawl.

**Comment by andburn** [comment]
If they ever do break the constructed rules, your Arena/Brawl type is a good idea - it would be straightforward to implement too.

In the meantime, I made a test build of HDT with all the latest Pull Requests. So we can test out if the brawl game type works ok, amongst other things. You can get it over at my [fork](https://github.com/andburn/Hearthstone-Deck-Tracker/releases/tag/v0.10.7.1-beta) of HDT. If you give it a try, make sure to back up all you data first just in case :smile:

**Comment by GiggliG** [comment]
Great! I'll check that out tomorrow.

**Comment by GiggliG** [comment]
I didn't get a chance to test this out in the brawl, but have just installed it and will check it when this week's brawl opens up.

For normal use, it seems to be working fine. Is there anything you'd like to me to test specifically?

**Comment by andburn** [comment]
I just wanted to make sure if it was recording brawl games consistently. There might be a proper update soon, with Epix back :smiley:, can just wait until then.
