### ISSUE TITLE
Cards Drawn

### ISSUE THREAD

**Issue by alfapatito** [Epix37/Hearthstone-Deck-Tracker#1193]
Hello guys, I have a question. Is it possible to prevent the Deck Tracker from showing drawn cards? I usually stream and I like the idea of my viewers having a look at my deck, but I do not like that the overlay shows me what cards I have drawn, I managed to get rid of every other thing on the overlay BUT the tracking of the drawn cards.

That's it, can you point me where the option to turn that off is?

Thanks guys, great work, keep it up

**Comment by andburn** [comment]
I'm not sure if you want to turn off highlighting of the last drawn card, or if you want no deck tracking at all, just a static list of cards. You can turn off highlighting in `options > overlay > player`. If its just a card list you want, you can use `Export > Screenshot` function and display the resulting image on your stream. If you do use the screenshot function, you need to make sure the deck you want to screenshot is Selected and made Active (this is to avoid a possible crash, that should be fixed in next update).

**Comment by alfapatito** [comment]
Thank you so very much, the export screenshot option is the thing I need,
thank you
