### ISSUE TITLE
New game button dissapeared

### ISSUE THREAD

**Issue by askarmuk** [Epix37/Hearthstone-Deck-Tracker#1213]
After several games "Add new game" button had dissapeared. It appeared again after I had restarted HDT.

![new game button dissapeared](https://cloud.githubusercontent.com/assets/8628595/9251325/0d6019fa-41ec-11e5-97dc-6bdc164a65f9.png)

**Comment by Epix37** [comment]
You are in the "overall" selection. Select "Deck" in the top left and it will re-appear :).

**Comment by askarmuk** [comment]
Hmm strange. But ok.

**Comment by Epix37** [comment]
Well, "overall" contains games from all decks. You can access that without having a deck selected, meaning HDT wouldn't know which deck to add the game to at that point. That's why the button is only in the deck section.

I admit it's not the most elegant of solutions. I still plan on improving the whole stats screen in the future.
