### ISSUE TITLE
Still not tracking

### ISSUE THREAD

**Issue by KJImmy** [Epix37/Hearthstone-Deck-Tracker#1232]
So I tried both of the methods in the FAQ on the main page. I checked to make sure I had done them correctly, and when I did so the log file for Hearthstone appeared to be the same as the one for the Hearthstone Deck Tracker, and when I checked the config file for the deck tracker it said <HearthstoneDirectory>C:\Program Files (x86)\Hearthstone</HearthstoneDirectory> which seems correct. Is there still something I could have been doing incorrectly with those two methods? Are there any other possible solutions?

Hearthstone Deck Tracker notices when I've started up Hearthstone because it brings up the overlay, but it doesn't seem to notice when I've actually started a game.

**Comment by Epix37** [comment]
One last straw I can think of is that you might possibly have multiple Hearthstone installations? Make sure the one you point to is the one actually in use.

Otherwise please do the following: 
* Close and Restart HDT and Hearthstone
* Play a game (conceding a AI match is fine)
* Upload the hdt_log.txt found in `%AppData%/HearthstoneDeckTracker/Logs` to [pastebin](http://www.pastebin.com) and post the link to that here.

**Comment by KJImmy** [comment]
So I searched my C drive and it looks like I've only got the one. I did what you said twice and I'm posting both because the second time I didn't check the hdt_log.txt file until after I exited Hearthstone and I saw an error. So the first one is immediately after I conceded the game and I'm back on the deck selection screen, and the one that says 2nd is after I've exited out of Hearthstone entirely.

1st - http://pastebin.com/jXxjQXu3
2nd - http://pastebin.com/2qnRijUm

**Comment by Epix37** [comment]
This looks like it might actually help! 
The problem is right here: `Could not find a part of the path 'C:\Hearthstone_Data\output_log.txt'` - that's obviously not the correct path. 

Either HearthstoneDirectory in the config is for some reason set to only "C:\" or maybe it contains some invalid characters?

Try this: Close HDT, delete the config.xml, check if it works. If not, try setting the path again. If it still does not work please upload your config.xml to pastebin, maybe there's something weird going on.

**Comment by KJImmy** [comment]
Success! It worked right after I deleted config.xml, thank you so much for your help!!

**Comment by Epix37** [comment]
Great! No problem!
