### ISSUE TITLE
Newly added decks are sorted at the bottom, if sorted by Last Playing, since latest update

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1248]
Since the latest update (released a day or two ago), decks that are newly added are sorted at the bottom, if the list is sorted by "Last Playing (descending)". 

New decks used to be sorted at the top, and then the most recently played deck, and so on.

**Comment by Epix37** [comment]
Since the decks have never been played, this is arguably the way "last played" *should* be sorted. (Also see #1009)

I will look into adding an option that allows the old behaviour.

**Comment by culinko** [comment]
Yeah, I'm the one "responsible" for this. I agree that having newly created decks at the top is good, but I just found it weird that if you play some matches with other decks, the decks with no matches would be sorted randomly in the middle if you sort by Last Played. As you can see in the other issue, I already regretted it for the Arena (I resorted to using the Last Modified because of that). Sorry!

**Comment by GaryKing** [comment]
I'm sorting by "Last modified" for now, which is roughly similar to "Last played" for me.
