### ISSUE TITLE
Malorne bug

### ISSUE THREAD

**Issue by choinul** [Epix37/Hearthstone-Deck-Tracker#1290]
I've seen this bug 2 times. This time, it was playing the Arena. My opponent played Malorne card, and the Malorne card was displayed in green on both decks at the moment he was played.

I think the normal behaviour is to be green on the opponent deck after the deathrattle is triggered, isn't it?

Here is my log file :

http://pastebin.com/0dk8Baaq

Best,

**Comment by MechaLynx** [comment]
Are you using the latest release (v0.10.11)? I'm asking because there where changes with how this mechanic is handled recently.

Also, while I'm not the developer, the log file seems to indicate that the card was stolen from you, implying you had Malorne in your own deck. Is this correct?

**Comment by choinul** [comment]
Yes, I'm using version 0.10.11.

No I don't have Malorne in my own deck, I'm still playing it and there is no Malorne. If you need it for testing I can export my deck also? (I don't know how to do it for developpers).  It is the opponent that played Malorne. So perhaps the bug starts by a false stolen Malorne in the code?

Best,

**Comment by MechaLynx** [comment]
It appears that the logging has changed since 3.0.0 and the changes are still being figured out. It may just be that reading the log file produces a false conclusion.

I think the log file you posted is adequate along with the clarification of what happened. I don't think it's necessary (but then again, I don't really know for sure) but if you _do_ want to post your deck, assuming you _have_ imported it into HDT, you can just upload `PlayerDecks.xml` from `%USERPROFILE%\AppData\Roaming\HearthstoneDeckTracker`. Again, this is likely to be a side-effect of the recent changes and I don't think the deck is necessary, but that's how to provide more information.

One more detail though: Are you certain that HDT is showing you the correct deck? It's possible that it detected and used a similar deck _with_ Malorne for you, even though your current deck doesn't have it. Very unlikely, but just making sure.

**Comment by choinul** [comment]
Yes, I'm sure it's the good deck, it's a deck I just created in arena 1 hour ago, and the deck is named Arena 21-08 05:38, so it is the good one. And the card "Malorne" appeared on both side at the moment the opponent played it.

If I undestood correctly the xml file, this should be my deck :
http://pastebin.com/gdZV3RR7

I can make a screenshot if it is better to read.

By the way, thanks for the work done on Hearthstone Deck Tracker, this is a wonderfull tool ! :)
Best,

**Comment by MechaLynx** [comment]
The XML snippet should be good enough. Thanks for the clarifications.

I'm not the developer, but I'm sure Epix will appreciate the appreciation :P

**Comment by mvordeme** [comment]
The same just happened to me in ranked play. I am using the latest version of HDT, and I don't remember it happening before.

**Comment by MechaLynx** [comment]
The one common element I notice is that in both cases, the log counts the Malorne card on the opponent's deck as stolen on a previous turn.

**Comment by mvordeme** [comment]
The mage happened to pull it out of an Unstable Portal. That could be part of the problem.
