### ISSUE TITLE
Gold earned not working.

### ISSUE THREAD

**Issue by FishermanHS** [Epix37/Hearthstone-Deck-Tracker#1295]
Normally I use HDT as a way to track how much gold I've earned during the day.

It no longer works. It's stuck at "2/3 10/100" gold and no longer tracks the gold earned.

It worked perfectly fine up until the patch that broke a bunch of other stuff.

**Comment by MechaLynx** [comment]
This is a known problem and not related to HDT:

https://www.reddit.com/r/hearthstone/comments/3hhhxb/psa_casual_doesnt_give_win_gold_anymore/

The reason it's stuck is because HDT expects an update from the log files, but since Hearthstone isn't registering these changes anymore and apparently not logging them either, HDT has no reason to ever update the counter.

This will fix itself once Blizzard fixes this problem in Hearthstone.

**Comment by FishermanHS** [comment]
Damn, that's really lame. Hopefully Blizzard gets that fixed soon then. Thanks for the quick reply!
