### ISSUE TITLE
Auto Close Upon Opening?

### ISSUE THREAD

**Issue by Ragingbananaz** [Epix37/Hearthstone-Deck-Tracker#1327]
So I have downloaded and extracted, I open it and it brings up the login/register screen, but as soon as I either hit log in or register, it closes and is no longer running... Doesn't say anything, just doesn't work. Help?

**Comment by darius07** [comment]
I deleted the HDT app folder (to reset the settings) and start it again. After the login to hearthstats, I can confirm this issue.

P.S I don't know if exist but can we have a reset button for settings in settings? In case of corruption and such.

**Comment by darius07** [comment]
Found the reason:
From error log
[13:25:02]: Another instance of HDT is already running.
[13:25:13]: Another instance of HDT is already running.
[13:25:37]: Another instance of HDT is already running.
[13:28:19]: Another instance of HDT is already running.
[13:32:12]: Another instance of HDT is already running.

So you have to go to task manager to kill the process, because it is invisible both in taskbar/tray area.

**Comment by Ragingbananaz** [comment]
No running process in the task manager for me....

**Comment by Epix37** [comment]
If this is still a problem please check if you find any files in the "Crash Reports" folder in the HDT install dir. Also see https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-starting

Closing for now.
