### ISSUE TITLE
Updated three times today

### ISSUE THREAD

**Issue by Eldalon** [Epix37/Hearthstone-Deck-Tracker#1339]
Hey man,

first of all. Love the work! Enjoying the tracker. I only have one small problem.
After the TGT release there was an update, awesome as that is, it updates like three times a day for me (everytime I restart my PC, as it seems) and that is kind of a problem at times! Is this a common problem or something I did?

**Comment by MechaLynx** [comment]
There have been a lot of updates during the last few days because of the TGT release and various issues that appeared because of the changes. This isn't a problem, however, just to be sure, check the version number when there's an update to see if it's a new version, because if it isn't, it could be a bug or other problem.

If you want to make sure what's been going on isn't a bug, you can check the [release history](https://github.com/Epix37/Hearthstone-Deck-Tracker/releases) to see if it feels like the updates have been happening more frequently than the history shows. If you have HDT starting with windows it's likely that it's been checking for updates every time it starts, hence why it seems to update every time you reboot (then again, I'm not the developer, but that's how I understand it working).

**Comment by Eldalon** [comment]
Well, it did not update today. I felt like the update was always the same size, so I just assumed it is the same. Maybe it actually was more than one update! Thanks.
