### ISSUE TITLE
Card Name left blank in overlay, window, and Deck Tracker

### ISSUE THREAD

**Issue by decostandi** [Epix37/Hearthstone-Deck-Tracker#1355]
<b>This issue appeared after downloading the latest commit </b>(1878dbb2817950b94537b7afca313e698cb2eef9)

The overlay:
![dtracker bug](https://cloud.githubusercontent.com/assets/11915043/9552117/a3774dc6-4d83-11e5-9f4b-1ea9fa6d5b78.PNG)

The deck window:
![dtracker bug3](https://cloud.githubusercontent.com/assets/11915043/9552226/68e2a682-4d84-11e5-8386-56da7e8b6d10.PNG)

The deck tracker:
![dtracker bug2](https://cloud.githubusercontent.com/assets/11915043/9552218/63de5528-4d84-11e5-9a5c-90fc63a8de52.PNG)

**Comment by mediainfohelp** [comment]
The same thing has been happening to me for over a month, but only with the overlay.  I've deleted the tracker and the data in the app section and it still won't come back.

**Comment by Epix37** [comment]
This is related to your text size setting.  Don't ask me why but this seems to happen if your text size is set to e.g. 148%, but is fine at 147% and 149%.

Give changing that a shot.

**Comment by mediainfohelp** [comment]
Thank you Epix37, this worked :smile:.

I had my scaling set to 161% due to 4K monitor.

At 149% it did not work.  

At 150% it **did** work.  

At 160% it **did** work.  

At 162% it did not work.

I'm more than happy with it working at 160% scaling, so thank you for sorting that out, after I uninstalled and cleared the app data I had no clue what it could have been.

:thumbsup:

**Comment by decostandi** [comment]
Interesting, I had my scaling set to 115% so I dropped it down to 100% and
it was fine. I'm thinking it's an issue with text boxes not resizing
correctly?
