### ISSUE TITLE
Got Malorne from Sneed's, deck didn't recognize

### ISSUE THREAD

**Issue by Zupami** [Epix37/Hearthstone-Deck-Tracker#1360]
I got a Malorne on my board from Sneed's.
Enemy BGH'ed it.
I drew it the next turn and HDT didn't recognize the Malorne.
Don't know if you need more information than this, I didn't screencap it, but still got the replay.

**Comment by MechaLynx** [comment]
Malorne is known to be problematic.

Proof isn't needed, but the log file could be useful. [Here are the instructions](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) on how to do that, if you're up to it.

**Comment by Zupami** [comment]
Of course, here ya go:
http://pastebin.com/9cuz0Zw0
But I didn't find a single instance of the word Malorne in the file

**Comment by MechaLynx** [comment]
Cards are referenced only using their id, which for Malorne is `GVG_035`.

On line 1088, your Malorne is killed and HDT gets confused about the deck. This is similar to issue #957 and Malorne has other ways of confusing HDT, like in issue #1290.

Currently the state of Hearthstone logging is unclear, since there are also issues with tracking gold rewards from wins (#1278) and this seems to be the case with Malorne, due to its mechanics. Things will have to settle down a bit before this stuff can be fixed I guess.

**Comment by Zupami** [comment]
Thanx for the info :)
