### ISSUE TITLE
Opens then says "hearthstone deck tracker has stopped working"

### ISSUE THREAD

**Issue by liveoffmusic** [Epix37/Hearthstone-Deck-Tracker#1365]
i dont know what i did, i just downloaded it, even  though i think im going into computer science i know nothing about how to fix the code, i only know a tiny bit of javascript, can someone help me fix this, should i uninstall? thanks

**Comment by andburn** [comment]
Try uninstalling it, and try reinstalling .NET 4.5. Then reinstall the program.

**Comment by chucklu** [comment]
Could you upload the screenshot when you receive the message "hearthstone deck tracker has stopped working"
you can download the .net4.5 from http://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by ikefalcon** [comment]
I am having the same problem. I tried uninstalling and updating .net 4.5, but I was not allowed to install .net 4.5 because I already have a more recent version or equivalent version installed. After reinstalling I encounter the same issue.

![hstrackererror](https://cloud.githubusercontent.com/assets/12906034/9614495/2288371c-50c0-11e5-8a0f-9899f18bbdb8.png)

**Comment by liveoffmusic** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/14046728/9740184/4ed298ba-5621-11e5-87e7-2dee656a0cb7.png)

Thats the screenshot i used the file that says uninstall to uninstall and deleted the files

**Comment by chucklu** [comment]
@liveoffmusic  I am not sure if you know the eventlog viewer.
start menu --> control panel -->management tool -->event viewer-->windows log-->application
you can find what the exact problem cause the HDT crash
