### ISSUE TITLE
Some games don't appear

### ISSUE THREAD

**Issue by toteZitrone** [Epix37/Hearthstone-Deck-Tracker#1421]
Hy community,

I'm just using Decktracker since yesterday and overall it functions very well. But two times a played game just didn't appear on hearthstats. Decktracker itself got it (one arena run, one ranked game) and displays the win, but Hearthstats simply doesen't. All other games, arena as well as ranked appear properly. 

I also get that flashing card-list thing, BUT Decktracker itself counts that game, what seems different from the problems other people have had.

**Comment by Epix37** [comment]
* Arena matches only get synced to hearthstats when they are actually on arena decks. Could this be the issue?
* Matches with mode "None", "Practice", etc.. are not. Maybe the mode detection failed? You can check this under `STATS > GAMES & STATISTICS > Games`.
* The flashing problem will be fixed with the next update (and is already fixed in the current pre-release: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases)

**Comment by riQQ** [comment]
Disabling `Auto deck selection` in the main menu works around the overlay flashing problem.
