### ISSUE TITLE
[REQUEST] Export to Heartharena

### ISSUE THREAD

**Issue by JeromeDane** [Epix37/Hearthstone-Deck-Tracker#1445]
Would love to be able to export win/loss matches to Heartharena so we don't have to enter them manually there. Is this already implemented and I'm just missing it?

**Comment by riQQ** [comment]
I'd love that, too. I wrote a little program for uploading my arena runs of my csv sheet to Heartharena. Maybe I'll try to integrate it into HDT.

**Comment by GiggliG** [comment]
That would be a great plugin riQQ.

**Comment by JeromeDane** [comment]
Do you all have any documentation on getting started writing HDT plugins our getting started with contributing to HDT in general? The version of visual studio I have installed was woefully inadequate when it came to opening the project, and I'd rather not have to reverse engineer everything in order to get started. I haven't taken the time to look carefully, so feel free to tell me to look harder if that's the answer. ;-P

Thanks for a GREAT tool. It's 1.8 billion times better than the original pixel based auto uploader I wrote for http://hearthstats.net a while back.

**Comment by riQQ** [comment]
Visual Studio 2015 Community Edition is free and should be able to open the project (https://www.visualstudio.com/en-us/downloads).

There's some documentation for writing plugins in the wiki, but i think it's outdated since there have been some bigger changes recently:
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Creating-Plugins

And you can take a look at other plugins:
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Available-Plugins

And there's a chat room at https://gitter.im/Epix37/Hearthstone-Deck-Tracker, where you can ask questions.

**Comment by x-ProgrammEd-x** [comment]
This would be an awesome addition. Upvote!

**Comment by riQQ** [comment]
I finally made it: https://github.com/riQQ/Hearth-Arena-Uploader.

**Comment by Cu8eR** [comment]
@Epix37 - this can be added to wiki under plugins tab

**Comment by riQQ** [comment]
I added it to the wiki. So i guess this can be closed.
