### ISSUE TITLE
Not showing up in stream

### ISSUE THREAD

**Issue by Kylehussong** [Epix37/Hearthstone-Deck-Tracker#1473]
So far the app works great and I'm really enjoying it, but I downloaded it for streaming purposes and for some reason it doesn't appear in any of my streams or youtube videos. Any suggestions?

**Comment by Epix37** [comment]
OBS and similar software are not able to capture transparent windows (i.e. the overlay window) as far as I know.

You currently have two options:
* Use screen capture rather than window capture.
* Enable `options > overlay > deck windows: player / opponent` and capture those separately.

There used to be a 3rd option, that **doesn't work with the current release**: the [HDTCompatabilityWindow Plugin](https://github.com/stdscatchemall/HDTCompatabilityWindow). But it is likely to be fixed some time in the future.

**Comment by Kylehussong** [comment]
I use xsplit for my stream. I tried both methods,  but screen capture gets me a blank screen and player window just shows the deck tracker app

**Comment by Epix37** [comment]
I have never really used any streaming software so I can't provide much more help than the above, sorry. 

An old issue (#52) mentions enabling "Capture Layered Windows", maybe that helps?

There are several streamers out there using either of those methods, so it has to work somehow? :/
