### ISSUE TITLE
Issues with Lag

### ISSUE THREAD

**Issue by MalevolentMiles** [Epix37/Hearthstone-Deck-Tracker#1475]
I've noticed an ongoing issue with response time by HDT after v11.0, but before v11.3. When I open HDT, it gradually takes longer and longer to respond (like altering cards in a deck, switching to another deck, showing what cards have been used/drawn) as I use it. It will eventually become so sluggish that it seems like it's frozen. If I close and re-open HDT, the cycle repeats. I'm sorry if this issue has already been addressed here.

**Comment by Epix37** [comment]
Give this version a shot: https://github.com/Epix37/HDT-Test/releases/tag/v0.11.4PRE1
Let me know if it's performing any better.

**Comment by MalevolentMiles** [comment]
So far, it's working much better. Thank you.

**Comment by Epix37** [comment]
There seems to be an issue with my fix (998b9a2) when it comes to asian hearthstone clients. 
 
Simplified example:

First loop:
```
offset += 4k
readblock(4k buffer)

// lines read:
half of line n-3 // buffer full, perfectly fine
line n-2 
line n-1
line n

offset -= length(half of line n-3) //because that wasn't actually processed
```


Second loop:
```
offset += 4k // offset is "4k + 4k - half of line n-3" at this point
readblock(4k buffer)

// lines read
half of line n-5 // buffer full
line n-4
line n-3
part of line n-2  // not supposed to happen!
```

Works perfectly fine if HS client is set to non-asian language. 

Things I noticed/tried:
* Seems to always be about 1.5 additional lines
*  `using (var sr = new StreamReader(fs, Encoding.UTF8))` makes no difference
* log files from asian clients contain a line of null characters (\0) at the end. The length of that doesn't seem to correspond to the number of additionally read characters though.

Anyone any ideas? :S

**Comment by Epix37** [comment]
I more or less figured this out... I think.

It works when I set the StreamReader encoding to ASCII. That obviously means all UTF8 characters come out as '?' but that doesn't really matter here anyway.

Now the main question is: Do I need to to use Encoding.ASCII or Encoding.Default (because it's system specific?).

**Comment by Epix37** [comment]
@chucklu could you test this? (or maybe you just know :))

**Comment by chucklu** [comment]
ok,I will check this issue

**Comment by chucklu** [comment]
under version v0.11.3,I can not reproduce this issue.

**Comment by Epix37** [comment]
What I meant:

Using a build that includes 998b9a2 (not released), does the behaviour I describe [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1475#issuecomment-140684557) still occour with the solution (not yet implemented!) described [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1475#issuecomment-140699836)? 

So, does the problem still occour on your system if you set the [StreamReader](https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/998b9a2339dd4b1e1352335cce1b81e0a71deb64#diff-26040afa5184391034842ca4bc01f6a1R150) encoding to Encoding.ASCII / Encoding.Default? Both? Neither?

You should be able to test it by starting HDT mid-game. If no cards are tracked the encoding doesn't work.

**Comment by Epix37** [comment]
Simpler: 
I created 3 builds with the different encodings. Which one(s) work(s) when you start HDT mid-game?
https://github.com/Epix37/HDT-Test/releases/tag/v0.11.4PRE3

**Comment by chucklu** [comment]
ok,I am downloading the file

**Comment by chucklu** [comment]
@Epix37  none of them works well.
all of the preRelease cpu usage increase more than 50%

**Comment by Epix37** [comment]
Weird, but not the answer to my question :/.

**Comment by chucklu** [comment]
HDT almost died cause it occupy more than 50% cpu

**Comment by Epix37** [comment]
You are right, weird that I didn't notice that before. I'll fix it and upload the 3 versions again later.

**Comment by Epix37** [comment]
Ok I finally got around to this, sorry for the delay. 

|Encoding (Download)|Hearthstone Language|Behaviour|
|---|---|---|
|[Default](https://github.com/Epix37/HDT-Test/releases/download/v0.11.4PRE3/Hearthstone.Deck.Tracker-v0.11.4PRE4_DEFAULT.zip)|koKR|not tracking|
|[UTF8](https://github.com/Epix37/HDT-Test/releases/download/v0.11.4PRE3/Hearthstone.Deck.Tracker-v0.11.4PRE4_UTF8.zip)|kokR|not tracking|
|[ASCII](https://github.com/Epix37/HDT-Test/releases/download/v0.11.4PRE3/Hearthstone.Deck.Tracker-v0.11.4PRE4_ASCII.zip)|koKR|works|

UTF8 (and as it turns out, DEFAULT) work fine in the first game after starting Hearthstone but no longer in any subsequent ones.
