### ISSUE TITLE
Compatibility with other apps

### ISSUE THREAD

**Issue by Nymeriaska** [Epix37/Hearthstone-Deck-Tracker#1483]
Since the release last week, other apps don't work when HDT is running (track-o-bot for example). This is not a issue from Track-o-bot but from HDT. Is that possible to fix it ? 
Both apps are very good.

**Comment by Epix37** [comment]
v0.11.0:
* Instead of using the `output_log.txt` HDT now gathers it's data from the `Hearthstone/Logs/*.log` files. For this the `log.config` was changed to only use FilePrinting instead of ConsolePrinting. If you for need ConsolePrinting enabled for some reason, you can set `LogConfigConsolePrinting` in the `config.xml`.

ConsolePrinting (i.e. output_log.txt gerneration) is the main reason for performance issues a lot of users were experiencing. That's why it's off by default now. `options > tracker > settings > open appdata folder` is where you can find the config.

**Comment by Nymeriaska** [comment]
Yeah i know. Maybe i'm too newb, but when I enable LogConfigConsolePrinting in this file, it works, but when HDT restart, i have to changed it again. I don't know how to make the change permanent. :/

**Comment by Epix37** [comment]
Make sure to close HDT before editing the config (should have probably mentioned that :))

**Comment by Nymeriaska** [comment]
Seems to work, thanks !
