### ISSUE TITLE
HDT Adds Multiple Games To Deck's Stats

### ISSUE THREAD

**Issue by Spedwards** [Epix37/Hearthstone-Deck-Tracker#1509]
Every now and then, HDT will go haywire and add multiple games to a deck's stats. I have no idea what causes this but the time it happened here was right after I exported a deck to the game (Warrior). HDT then recorded 16 games against my Warlock deck but the deck name was the Warrior one.

![adddngn](https://cloud.githubusercontent.com/assets/3257096/10020742/e50002f2-6187-11e5-93db-8307b83f6625.png)

**Comment by GaryKing** [comment]
Yep I've been having this problem too recently. I'm not sure what causes it, or how to fix it. I usually just try a combination of restarting Hearthstone, HDT, etc. until it's fixed.

**Comment by Epix37** [comment]
I think I found and fixed the issue. I'll release a beta update later today. Please see if that still happens with that.

**Comment by GaryKing** [comment]
I noticed that when this problem happens, it seems to be because the last recorded game was not completely recorded. For instance, in the last game that was recorded before it kept getting recorded multiple times, the log finished on Turn 10 even though the game ends around Turn 15. So to fix the problem, I had to remove the game from HDT so that HDT wouldn't continuously try to "complete" that game.

It looks like your latest changes should fix this, so hopefully it does indeed.

**Comment by Epix37** [comment]
Okay no beta update, I don't feel like writing update notes right now.

Buit here is a test release: https://github.com/Epix37/HDT-Test/releases/tag/v0.11.4PRE5

**Comment by culinko** [comment]
Does this still happen?

**Comment by GaryKing** [comment]
No
