### ISSUE TITLE
Hearthstone Deck Tracker gets stuck on startup

### ISSUE THREAD

**Issue by wk1111** [Epix37/Hearthstone-Deck-Tracker#1557]
When I try to run the Deck Tracker the loading icon pops up but the program never actually starts and I have to close it from the task manager. Task manager shows that while the loading icon is up it's using 30% of my CPU which seems unusual. I'm using the latest stable release. I'm running Windows 8.1 and I have .NET 4.5.

**Comment by Epix37** [comment]
Close Hearthstone and delete everything in `C:\Program Files (x86)\Hearthstone\Logs` (or your equivalent). See if this still happens.

If yes: This sounds like HDT does not actually crash but only gets stuck on the loading screen? Please go to "%appdata%/hearthstonedecktracker/logs", upload the hdt_log.txt to www.pastebin.com and post the log here.

**Comment by MarvelWild** [comment]
10:02:59 PM|Warning|Core.Initialize >> HearthMirror Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'int' because it is a non-nullable value type
   at CallSite.Target(Closure , CallSite , Object )
   at HearthMirror.Reflection.InternalGetGameType()
   at HearthMirror.Reflection.TryGetInternal[T](Func`1 action, Boolean clearCache)
