### ISSUE TITLE
Arcane golem is not exported into HS from HDT

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1636]
Arcane golem is not exported into HS from HDT

**Comment by Epix37** [comment]
Try re running the constructed setup under `options > tracker > exporting`. If it does not work after that it is most likely not fixable.

**Comment by Cu8eR** [comment]
No it is not working... also only one explosive trap was exported, the second one not... maybe is it fixable?

**Comment by Epix37** [comment]
Oh I for some reason though this was talking about exporting HS to HDT. 

I just tried exporting both Arcane Golem and Explosive shot, no problems there. 

Try messing with the speed and delay settings in `options > tracker > exporting`. Sounds like that is most likely the problem here. For reference: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting-is-not-working-properly--missing-cards

**Comment by Cu8eR** [comment]
I think it is related to to high speed of exporting. I will check

**Comment by Cu8eR** [comment]
Yes, thats it :)
