### ISSUE TITLE
Export Function: Deck Sorting Issue

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#1649]
The most common way to order the cards in a deck is to have them in mana cost order and then name order.

When you export a deck, you get them in the order you added them to the deck list.

Can you fix it?

**Comment by Epix37** [comment]
Exporting as/to what specifically?

**Comment by Elitesparkle** [comment]
> Exporting as/to what specifically?

I had noticed the problem using those:
- Export > Copy IDs to Clipboard
- Export >  Copy Names to Clipboard

This one should have the same issue:
- Export > Save as XML

**Comment by Cu8eR** [comment]
@Epix37 - alos there is a problem when you export cards from HS into HDT... they are not sorted by mana/name when you add another card into list manually in HDT

**Comment by WaxPaper** [comment]
I think what this guy's talking about it when you export a decklist, from one that you created or modified (after exporting from a website, for example) into the Hearthstone client, the automatic export "clicker" adds the cards into the client in the order that you added them to the decklist.

So imagine I import a deck from a website, and then I remove a card I don't have -- like the 8-mana Alexandra, for example -- and replace it with a 2-mana Loot Hoarder. When I export that deck list into the game, the Loot Hoarder will be added last, after higher-costing cards.

That's just an example to help you figure out what this guy is describing. The end result is still the same, of course... That's why you probably don't get more people bringing it up as an issue, because it's probably just more of an OCD thing for some people. The majority of us don't really care what order the cards are added into the decklist, knowwhatImean? ;)
