### ISSUE TITLE
Problems Exporting a Deck

### ISSUE THREAD

**Issue by antarcticwind** [Epix37/Hearthstone-Deck-Tracker#1655]
I am unable to export decks to hearthstone. Before today, I've never encountered any problems with exporting before.

I noticed the following when exporting:
1. It keeps clicking Deck Helper even though it is a new deck (I presume it was trying to clear the deck)
2. A message appears, asking me to "use the friends menu to communicate with a friend"
3. Next, it is able to change the name of the deck successfully
4. Finally, it searches for the cards that are supposed to be added, one after another, but never adds any.

Curiously, when I tried a different deck, it managed to add Feugen and Stalagg.

Today, I've tried the following proposed fixes, but none of it worked:
1. Set Hearthstone to run in compatibility mode for Windows 7 (I use Windows 10)
2. Set the speed for exporting to "Very Slow"
3. Unchecked "Auto Clear Filters"

I'm at a loss. Anyone have any ideas?

**Comment by andburn** [comment]
This is strange, seems to be the same problem as #1654.

Not sure what to suggest since you've already tried a few things. Are you running hearthstone windowed or fullscreen? It could be worth trying fullscreen if your not already. Did you get the message in the deck tracker telling you are missing all the cards from the deck? Can you think of anything you might have changed or added recently, like a plugin or something?

The key has to be with Feugen & Stalagg because they're treated a bit differently when exporting. Do you have golden versions of them?

**Comment by antarcticwind** [comment]
Hmmm, I'm pretty sure it's fullscreen; in the in-game options, "Fullscreen" is checked.

I indeed got that message in the deck tracker, saying that I am missing all the cards.

I have only the non-golden versions of Feugen and Stalagg.

I also can't really think of anything that might have changed, except the new HDT version?

Yeah, I am quite at a lost too. Please help,

**Comment by antarcticwind** [comment]
Strangely, I tried to export a deck again today, and it worked like a charm, without me changing anything. I guess it is a non-issue now.
