### ISSUE TITLE
Crash on start after update

### ISSUE THREAD

**Issue by WaxPaper** [Epix37/Hearthstone-Deck-Tracker#1670]
Got this crash actually before the update once (I think) but definitaly after the latest update... It's actually crashing every time now, right after I choose the "Continue as Guest" login option for Hearthstats.

Here's the pastebin with the crash log:

http://pastebin.com/PGebMbkD

**Comment by Epix37** [comment]
You could be missing some files, I'm not really sure. Try downloading the latest version again and make sure to unzip everything: https://github.com/Epix37/Hearthstone-Deck-Tracker/releases

**Comment by WaxPaper** [comment]
It just happened to work this last time I tried to open it now, without downloading it and reinstalling it or anything... Strange that I was getting those force-quits every time and now I'm not.

Ya know, one thing I have been wondering about -- because I usually get an average of 0.5 crashes per session, on average, over the last couple months -- is if the number of decks that you have saved can influence the stability and/or speed of the program. I don't know how many decks I have saved exactly, but my PlayerDecks.xml file is 2.20 MB, so it's a lot; at least a couple hundred decks.

Does the database engine (it's JSON, right) usually have trouble with a high number of records? Could this cause crashes, as well as slow-downs? (I've noticed that app runs a lot slower than it used to, especially noticeable when I need to click things like marking tags -- the app hangs for about 5 seconds after each tag I select, for example).

If the answer is yes, are there open-source JSON tools that allow you (me) to compress or clean/"vacuum" the database files? Any sort of maintenance that the user can perform? Or is it pretty much just a matter of trying to keep your databases as small as possible?

Thanks man...

**Comment by Epix37** [comment]
The size should be no issue when it comes to crashes, slowness might be the case. Do you archive decks you no longer actively use? That could speed things up considerably. 

No way to tell where the issue could be without seeing crashlogs. Could you upload the ones from the past month?

**Comment by WaxPaper** [comment]
I haven't started using the archive function yet much, no... But it sounds like I should, so I will! Here's a link to the crash reports zipped in a file, by the way:

http://s000.tinyupload.com/index.php?file_id=00867679523341638155

But don't worry too much about it on my account, unless you wanna try to debug the issue in general, for stability and whatnot... I've been using the same install (well, the same portable folder location linked to my appdata folder after you included that ability) since the beginning, so it could be possible something's been corrupted along the way. I need to get around to cleaning up my deck database and maybe even wiping the appdata location to start fresh, and just import the decks and stats or whatever.

Thanks for the continued developments!

**Comment by Zonnza** [comment]
I have a similar issue as Wax is having.  On 13.0 ver and up, I always gets a crash of the client.
But when I DL'd the last version before 13.0 (12.2), it works just fine.

The crash happens always at the same spot:
1) I double click to open the tracker, it does the quick loading window into the sign in screen.
2) Since I never made an account, I just hit the continue as guest, then continue anyway.
3) This is where it "crashes." The loading splash screen comes up and within a short delay (~1sec), I get a windows "hearthstone Deck Tracker has stopped working" window pop up with the check online for sol and close the program.

If I check task manager, it shows "SplashScreenWindow" process as not responding while "Hearthstone Deck Tracker" still running. After a while, the splash window goes away and until I hit close the program on the windows crash window, it keep the Tracker process as "running."

I attempted to try and find a solution by DLing the old tracker and deleting the massive amounts of old arena decks and such I left in the list, this didn't help.  I noticed that in 13.0 and higher, there a few DLL's included now with the tracker, not sure how those interact.   

If Wax's issue is over, we can move this to a new thread.
Also quick question, where does the tracker keep the info on the decks we make? Seems like a app data location or some other location I'm unaware of.

Thanks for your time,
Mike

**Comment by Zonnza** [comment]
I added the config line and have reinstalled .Net framework, removing 3.5 and installing 4.0 with it then updating to 4.5 by itself. The splash window no longer functions but the same issue still happens. I'm tech savy but not familiar too much with this type of work since I never delved much into scripting or XML, but I will try to assist in any way to help find a solution.  

I renamed the appdata tracker folder with an added "-old" to it and ran the tracker again for it to generate a new folder, same result with crash, except this time the app didnt take the ~1 sec to crash when splash was starting, it did it almost immediately after I hit continue anyways button..  The problem report was this:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	hearthstone deck tracker.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	563382c3
  Problem Signature 04:	HearthstoneDeckTracker
  Problem Signature 05:	0.1.0.0
  Problem Signature 06:	563382c3
  Problem Signature 07:	399
  Problem Signature 08:	1c9
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt


--------------------------

I deleted the new appdata folder after and changed the name to remove "-old" from the previous one, and this is the problem detail I got from that run:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	hearthstone deck tracker.exe
  Problem Signature 02:	0.1.0.0
  Problem Signature 03:	563382c3
  Problem Signature 04:	HearthstoneDeckTracker
  Problem Signature 05:	0.1.0.0
  Problem Signature 06:	563382c3
  Problem Signature 07:	399
  Problem Signature 08:	1c9
  Problem Signature 09:	System.NullReferenceException
  OS Version:	6.1.7600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Ended up being the same problem it seems.  And I personally do not know how to analyze the details, so I hope it helps you.  I can also include crash reports if needed.

**Comment by Zonnza** [comment]
Here is a rar of the crash reports if needed:  http://s000.tinyupload.com/?file_id=75341501802839814326

**Comment by Epix37** [comment]
1) Data is stored at %AppData%/HearthstoneDeckTracker. Make sure to make a backup and don't just  delete everything in case it has nothing to do with the problem / is easily fixable :).
2) Edit the config.xml and set "ShowSplashScreen" to false. If the setting doesn't exist, add this line `  <ShowSplashScreen>false</ShowSplashScreen>`. See if thats helps.
3) If you are not on windows 10 try reinstalling .NET Framework
4) If nothing helped, could you post the problem detail here? Should be listed under "Problem Reports", [see here](http://windows.microsoft.com/en-us/windows-vista/view-the-details-of-a-problem-report).
