### ISSUE TITLE
Crashing after try to move deck of current brawl match

### ISSUE THREAD

**Issue by shamanix7** [Epix37/Hearthstone-Deck-Tracker#1673]
I played a Brawl (Spider Brawl), HDT recorded a match to the current active Deck (a shaman deck, but Brawl was with Hunter). Afterwards I tried to correct some data on this record as it has no opponent name and no opponent class in the statistics. Pressing 'Edit Game' will crash HDT.

Note: The second Brawl match is shown correctly in the statistics and can be edited.

**Comment by Epix37** [comment]
Please upload the crash log: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Epix37** [comment]
The link above is not quite right, I mean the log file that is mentioned in the crash dialog.

**Comment by GiggliG** [comment]
I have found a number of games where the Opponent Class is not saved (in the decks xml file it is an empty listing instead of, say, <OpponentHero>Hunter</OpponentHero>).

For these games, if I try to edit the game data, it crashes HDT every time.

I tried to upload a crash report but it said this requires write permission to this repository.

**Comment by culinko** [comment]
Closing in favor of #1765.
