### ISSUE TITLE
Warning message: ### cards are missing in the left top corner

### ISSUE THREAD

**Issue by Cu8eR** [Epix37/Hearthstone-Deck-Tracker#1707]
Warning message: ### cards are missing in the left top corner when the game starts. It is not shown always

**Comment by Epix37** [comment]
Can you elaborate? I don't understand the issue.

**Comment by Cu8eR** [comment]
There is a message in the top left corner sometimes when the match starts during cards selection... it is shown for about 3 sec, it is really difficult to take a screenshot

**Comment by riQQ** [comment]
And what's the problem with this message? Is it shown when it shouldn't be or vice versa?

**Comment by Cu8eR** [comment]
Yes, it shows that these XXX cards are missing in my deck, but they are in my deck and they are shown in the right panel. Also when I pick them or use, they are shadowed in this panel... it happens sometimes, maybe problem with sync between HDT and HS?

**Comment by culinko** [comment]
Do you have correct deck selected when queuing for a match?

**Comment by Cu8eR** [comment]
Auto select deck feature is enabled... anyway I also select this deck manualy before I go into queue

**Comment by depechenode** [comment]
Auto deck selection works for first game upon start up.  however...when switching decks Auto Deck no longer works and manual selection has to be done.  This is despite the Auto Deck selection being checked.  The Warning message for invalid cards appears due to the Auto Deck NOT switching.  This has been an issue for the past 4 mini updates.
