### ISSUE TITLE
Question: chess-like notation of a game?

### ISSUE THREAD

**Issue by sebastientromp** [Epix37/Hearthstone-Deck-Tracker#1768]
Hi,

Thanks a lot for the tracker! I've started using it a few days ago, and am trying to build a way to replay the games online (via a javascript player probably).

I'll be trying to simplify the replay.json file, since I don't need as much data as what is present in the file. Something I'd like to do is to build a chess-like notation for HS game moves (that could be read and written concisely by a human who understands the notation), and was wondering if it was something you had already thought about.

Thanks again for the tracker :)

**Comment by Epix37** [comment]
Not really human readable but there is a replay format now: http://hearthsim.info/hsreplay/

A web replay viewer is currently being worked on by the HearthSim community as well: https://github.com/HearthSim/joust

You can find more information about hearthsim here: http://hearthsim.info/, including an IRC channel.

**Comment by sebastientromp** [comment]
Thanks for the pointers!

I've just joined the IRC channel, and will probably have a few questions :) I will give a try to build a more condensed notation (as this would allow people to actually "play moves" just by giving comments) and let you know if I achieve something.

As for the XML replay, do you have any idea when it will be integrated in HS Deck Tracker?

**Comment by jleclanche** [comment]
@sebastientromp the problem is that the Hearthstone state is much more complex than chess', so a replay format has to track not only what moves were made, but everything that resulted from it.

If you *just* want the player's plays, you can strip everything but the SendOption tags as it's always about "Here are your `<Options>`, pick an option and send it with <SendOption>`", but it doesn't seem particularly useful.

For example, in chess, board state is predetermined at the beginning of a game. Here in Hearthstone, you have to create all the entities first. Which hero are you using? Which hero power do you get with it? Which cards have been dealt to you?
Additionally, when the *opponent* plays something, it's not enough to say "Opponent played Fireball on x". You have to already know that the opponent had a card in hand, and that card became fireball, otherwise you don't know how many cards the opponent has in hand. So now you have to keep track of reveal/unreveal.. etc.

All in all I simply do not see a way to create a human readable notation that is also programmatically usable. You *can* make the hsreplay format human-readable by adding names to attributes though.

**Comment by jleclanche** [comment]
Ping me on the `#hearthsim` channel if you want to talk about this further.
