### ISSUE TITLE
Paladin secret bug

### ISSUE THREAD

**Issue by SirSeran** [Epix37/Hearthstone-Deck-Tracker#1771]
Hi there,

I just finish a game that showed me a bug in the paladin secret greying:

Turn 3 opponent played AVENGE
Turn 4 opponent played PILOTED SHREDDER
Turn 5 I killed the Shredder (AVENGE was greyed and only secret posible Sacred Trial) and opponent played more minions.
Turn 6 I kill a minions and booom AVENGE triggered.

Basicly I think Avenge was grey because I killed a minion when the secret was there and a minion from the Shredder was summon but it did not take in count the fact that the secret was played before the Shredder. OR the introduction of Sacred Trial made a weird interaction with the greying.

**Comment by ThePsionic** [comment]
Seems like fun happenings with Avenge. Per the wiki:
* Like all death-related triggers, Avenge may activate before or after the dying minion's Deathrattle, depending on the order of play. This can be significant because Avenge only chooses a target when it activates, not when it first checks for trigger conditions. If the Avenge was put into play before the minion, it will select a random friendly minion and grant it the Avenge buff before any Deathrattle; while if the minion was put into play first, its Deathrattle (if any) will trigger before the Avenge.[7] This allows order of play to affect both targeting and activation.
* If this Secret is active while a friendly minion is killed, but there are no others on the board, it will remain hidden and not activate.

**Comment by Epix37** [comment]
Fixed the obvious bug, not sure how to handle more complicated, admittedly rare, situations though. See commit message for details.
