### ISSUE TITLE
Problems importing decks with Baron Geddon

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#1907]
If I import a deck with Baron Geddon, such as [this deck](http://www.hearthpwn.com/decks/325055-update-unbeatable), then Baron Geddon appears in the HDT deck list as a 0 mana "Hero" card. 

Therefore, when exporting a deck to Hearthstone, HDT doesn't do anything because it doesn't understand what the card is.

**Comment by riQQ** [comment]
See #1883.

**Comment by GaryKing** [comment]
Yes same issue. I'm not sure why the other issue was closed though when it hasn't been resolved yet?

**Comment by imsomony** [comment]
For anyone stumbling across this as I have... the creator has added this issue (and resolution) to the NEXT update for the deck tracker. Currently, we are version 0.13.7, and the fix for this will be in version 0.13.8.

What I did to work around this is to remove Baron Geddon from my deck in HDT. Insert anything else at all, doesn't matter, although I suggest a zero-mana card to make it easier. Then export to Hearthstone as normal. Once the deck exports, remove the random card you added, and manually add Baron Geddon.

**Comment by GaryKing** [comment]
@imsomony You don't have to do it that way. You can just import the deck into HDT, edit the deck, remove Geddon, then re-add him. Then it will export just fine.
