### ISSUE TITLE
suggestion: Auto-squelch

### ISSUE THREAD

**Issue by KayaTheRock** [Epix37/Hearthstone-Deck-Tracker#1986]
Hello

It could be nice to have an option to squelch the opponent automatically at the start of the first turn.

Thanks

**Comment by Jecoms** [comment]
That would be directly interacting with the game client instead of just displaying information. It would be akin to botting and it could flag you as using 3rd party software that violates the TOS. The reason this program is tolerated by Blizzard is because it is just tracking readily available information for you. It's not playing for you or making decisions for you.

**Comment by KayaTheRock** [comment]
I understand your point, but at the same time, there is the "export to hearthstone" function, which arguably does interact with the client as well. It does what you chose to do automatically. In my opinion, the auto-squelch would be exactly the same principle. 

But I totally understand if you chose not to implement this.

**Comment by culinko** [comment]
For me, there's a difference between automating stuff before queuing into an actual game and automating stuff inside of a game. So I wouldn't want this to be implemented either. But you are correct, there is some automation already.

**Comment by Epix37** [comment]
I try to avoid any interaction with the game during gameplay - as correctly assumed here. 

This feature will currently not be added.
