### ISSUE TITLE
Ranked marked as Casual since 0.13.8

### ISSUE THREAD

**Issue by Patrick7840** [Epix37/Hearthstone-Deck-Tracker#2034]
I have the common issue that ranked gamed marked as casual games and get satistik tracks under casual. I tried to change fullscreen / windowed and res. changes. Nothing happend. The problem is since the update 0.13.8 -> i tried the older version and there its finde and the problem doesnt exist. When i switch so 13.8 it happen again :S :(

**Comment by Epix37** [comment]
This did not happen with 0.13.7?

**Comment by Patrick7840** [comment]
Nope, with 0.13.7 its all totaly fine :) ... I googled and searched for solutions but didnt find anything that worked ...

**Comment by tknights2015** [comment]
Issue is also with 13.9 version

**Comment by Verile** [comment]
I have the same issue with most of my ranked games recording as casual.  It only seems to happen when I'm in full screen mode in hearthstone though.

**Comment by terroriza99** [comment]
This problem is extremely frustrating when trying to track things over a few days of playing. If I only play ranked games which I do then I guess I can just view casual stats and it will work somewhat. Another issue is that when you go to hearthstats dashboard it is somehow mixing up and leaving games out. I installed this program yesterday and all was fine, I also played around 25 games on my main deck with it. Today all games show up as casual and I play another 30 games on my main. When I go to the website it only shows that I have played what appears as some random number of total games with said deck.

I added up both my casual / ranked games and the number of games it shows I played online is neither of these numbers nor the combination of the two. What makes things even more strange is that I just now made a random deck and played 2 quick games in ranked. I go to the website and it shows I played 2 games no problem. I really wish this program would work correctly, It looks much better than others out there, but I might be forced to switch.

**Comment by Epix37** [comment]
Please take a screenshot during several ranked games via the HDT hotkey (set up under options > tracker > hotkeys) and check if any of them are empty.

**Comment by tknights2015** [comment]
Screen shots using HDT  hot keys during this game. All are blank.
[log_1122016-174232.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/127337/log_1122016-174232.txt)

**Comment by Epix37** [comment]
Give this version a try: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.10_PRE2

**Comment by tknights2015** [comment]
v0.13.10_PRE2
1. Played 2 ranked  games.Both were recorded correctly.
![ranked games](https://cloud.githubusercontent.com/assets/16232528/13015935/204fd8bc-d179-11e5-8c39-5b12b10c16ff.JPG)

2. Exported a deck to Game- Worked correctly and all cards were added to deck correctly
3.Flavor Text tool tips were displaying in game, but are also displaying when game is minimized and not in a game.
![tool tip](https://cloud.githubusercontent.com/assets/16232528/13015796/4760c0c0-d178-11e5-8b79-ca46e05a9cf1.jpg)
![hearthstone screenshot 02-12-16 11 02 30](https://cloud.githubusercontent.com/assets/16232528/13015798/4e21e204-d178-11e5-9004-26bdbe573ff3.png)
Game Screenshot hotkey - Worked for first 2 screen shots. All after this were blank.
Played and additional ranked game and restarted HDT still blank screen shots. Below are screen shots in order taken from the 2 ranked games.
![screenshot and logs 2](https://cloud.githubusercontent.com/assets/16232528/13015946/2cb32f14-d179-11e5-99b7-e48be5511707.JPG)
![screenshot and logs 2](https://cloud.githubusercontent.com/assets/16232528/13015950/31328b34-d179-11e5-9235-4410a256ba27.JPG)

Log from testing
[log_1222016-105351.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/128412/log_1222016-105351.txt)

**Comment by tknights2015** [comment]
Hi,
I did not know where to post results ( whether on the new pre release or issue #2034) I posted on the #2034  Sorry if this is the incorrect place/
 
TK

**Comment by Epix37** [comment]
@tknights2015 can you doublecheck you used the "Game Screenshot" and not infact the "Screenshot" hotkey action? Those should not include the overlay :/.

**Comment by tknights2015** [comment]
I did not use the Game screenshot key. I used the screenshot. Will test with the Game Screen hot hotkey and report back. Also, I just restarted HDT and Heartstone and took 5 screenshots with the screenshot hot key and none were blank. With nothing else changed.

**Comment by Epix37** [comment]
Well, I changed nothing about the normal Screenshot hotkey functionality.. apparently same behaviour as before where it just started working again at some point. 

Rank(ed) detection no longer uses that method of taking screenshot, but the "game screenshot" one.

**Comment by tknights2015** [comment]
Game Screen shot also appears to be working correctly. 5 taken in last game, all correct.

**Comment by tknights2015** [comment]
Just for reference. I downgraded back to 13.9.  First screenshots taken in ranked ( 2) were blank. I restarted HDT from within the app and the next screen shot worked. Ranked game recorded correctly
Log file
http://pastebin.com/PgH8AYaM

**Comment by Epix37** [comment]
what version of directX are you using? (win > run > dxdiag)

**Comment by tknights2015** [comment]
Version is DirectX 11

**Comment by terroriza99** [comment]
I think I figured out how to fix it, well at least for me anyway. When I turn stats into view in it's own window then it causes this problem. I went back into the settings and changed it back so that when I view stats it does not open it's own window. It's opens it in the same window and I just hit the back arrow to go back.

I tested this a few more times switching off and on and it's definitely what's causing the problem for me. I switch the setting back and have had no issues since. Everything is running great.

**Comment by tknights2015** [comment]
V13.11 ranked records correctly with the alternative screenshot enabled.  Screenshots also correct using "Game Screenshot" hotkey.

**Comment by Epix37** [comment]
Perfect. Can anyone else confirm?

**Comment by Gr3yz** [comment]
I'm on V13.11 and game screenshots are working, but still getting ranked games recorded as casual.

**Comment by Epix37** [comment]
@Gr3yz With and without `options > tracker > settings > alternative screen capture` enabled?

If so, please make a screenshot with both hotkeys actions (screenshot, game screenshot) and post them here.

**Comment by Gr3yz** [comment]
@Epix37 Alternative Screen Capture fixed it.  Thanks a lot!

**Comment by Epix37** [comment]
The next release will automatically detect when the default screen capture fails, test the alternative one and enable the setting if it succeeds.

**Comment by Gr3yz** [comment]
Alternative Screen Capture (ASC) gave me another issue.  It correctly categorizes ranked games, but now the opponent deck does not show.  When I turn ASC back off, it starts working again.  Anything I can do?

Thanks.

**Comment by Epix37** [comment]
Are you sure it's related to the alt. screen capture being enabled?

My best guess is opening the friendslist triggered the deck list to hide but there was some issue revealing it again.

If possible, please reproduce the problem and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by Gr3yz** [comment]
I think I found why HDT isn't properly recognizing ranked games with alt. screen capture OFF for me.  I use another program to dim my screen a bit.  If I'm below 80-90% brightness, it doesn't recognize ranked games (sees them as casual).  But if it's 80-90%+, it seems to correctly recognize them.  

FWIW, HDT used to work fine with the screen dimmed 2-3 versions ago.  It only broke in the last couple of versions.

**Comment by Epix37** [comment]
Rank(ed) detection has been changed to image recognition with v0.13.6, because the old method was very unstable in a lot of cases.

Screen dimming software is a known issue, but with the default screen capture there is no way around it. If the alt. capture method fixes this, all the better.

Could you answer my previous question though?
> Are you sure [the missing opponent deck is] related to the alt. screen capture being enabled?
If possible, please reproduce the problem and post the log here. [See here.](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by Gr3yz** [comment]
I tried to recreate the missing deck with alt screen capture on today and was unable to.  You were right, it must have been some other interaction.  Everything is working fine on my end now.  Thanks a lot for the help.

**Comment by Epix37** [comment]
Very happy to hear that!
