### ISSUE TITLE
Arena decks should not be suggested when two decks are possible matches for the current deck

### ISSUE THREAD

**Issue by GaryKing** [Epix37/Hearthstone-Deck-Tracker#2058]
I have my Tempo Mage deck currently set as the active deck. I play a game, in Casual mode, with my Midrange Druid deck. HDT asks me whether the deck I'm currently using is my Midrange Druid deck, or one of my Arena decks.

HDT should immediately choose the Midrange Druid deck because I can't possibly be using an Arena deck in Casual.

**Comment by tknights2015** [comment]
Along the same, with Auto Deck selection enabled, not selecting the deck. Automatically opening a pop up with decks, even though there are limited deck options

**Comment by knoxius** [comment]
well you indeed CAN USE your arena decks in casual or in ranked play, if they do not contain MORE THAN 2 of any type of card in it. perhaps the issue here is that the HDT does not recognise that you are doing casual/ranked games when choosing a deck for you.

i guess it could be solved by: when doing casual/ranked/other it could only scan list of constructed decks, and when doing arena, scan just arena decks in the list. sorry, i am doing my thinking while writing, that's my process.

**Comment by GaryKing** [comment]
Yes that's what I'd like @knoxius. It should only scan Constructed decks in Casual/Ranked, and Arena decks in Arena.

I mentioned this issue before; at the time, the issue was that an Arena deck was auto-selected when I was playing in Ranked, and that was fixed, but this current related issue still exists.

**Comment by Epix37** [comment]
This should be fixed with v0.14
