### ISSUE TITLE
delay in event trigger for playing a card

### ISSUE THREAD

**Issue by falconmick** [Epix37/Hearthstone-Deck-Tracker#2064]
Just wondering why there's about a 1.2 second delay from the play of a card until the event fires. Is it how you get the event out of the game or is it a throttling thing you have put in place? I just need the ability to respond to plays as soon as possible. Cheers

**Comment by andburn** [comment]
Events should fire when a card is visually played. If you want it before that see #1672.

**Comment by Epix37** [comment]
Using GameState instead of PowerTaskList *can* be enabled in the config but is no longer supported by HDT and could cause problems. Chances are PowerTaskList is closer to the actual animation, especially when multiple animations are queued. GameState will log everything instantly in that case. 

Btw, [Gitter or IRC](https://github.com/Epix37/Hearthstone-Deck-Tracker#community) might be better suited for these kinds of questions.
