### ISSUE TITLE
GameEvents.OnTurnStart triggered twice for very first turn

### ISSUE THREAD

**Issue by ko-vasilev** [Epix37/Hearthstone-Deck-Tracker#2169]
I noticed that after OnGameStart event is fired, the next OnTurnStart event is called twice although the turn was not passed to opposite player.

**Comment by Epix37** [comment]
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/35a73cfa727423511875123ec84ddfb2342d278b and https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/ae57dc0e33b2fe3b7c7c7f62697b1af95cb373ef.

`GameEvents.OnTurnStart` still executes for each turn start when restarting the log readers.
