### ISSUE TITLE
Importing from hearthstone is always fwrong

### ISSUE THREAD

**Issue by Ansem93** [Epix37/Hearthstone-Deck-Tracker#2179]
hi.
I'm the only one that when try to import my deck from hearthstone, will import just a random deck with random cards?
like last time i did a normal deck with warrior:
- first time it created a deck with 36 cards, and out of this 20 cards only 2 were really in the deck
- imported the same deck, this time it HDT created a deck with 26 cards, with only 1 card from my deck

What's so wrong with import ? I tryied to import with innkeeper and everything was fine, I don't get why with innkeeper import seems to be totally random and unrelated from my decks

**Comment by Epix37** [comment]
If you collection changed since you first set up constructed importing, you have to run the setup again to let HDT know which cards are on the first page for each class. 

To do that: 
* enable `advanced option` (bottom left in options)
* `options > tracker > importing > set up constructed importing`. Also read the last page for information on why it (almost) always imports too many or too few cards.

I already explained to you why Innkeepers and HDT's importing work the way they do: https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2172#issuecomment-191406352.

**Comment by Ansem93** [comment]
Thanks for the help. Didn't know about this option. This time only missed 3 cards :)

P.s. while I was in the settings, i read about netdecks. What's that? it works with firefox too?

**Comment by Epix37** [comment]
I think this works for firefox as well: https://netdeck.n4ru.it/browser-bookmarklet/
