### ISSUE TITLE
HDT always imports two of the cards in my deck

### ISSUE THREAD

**Issue by YuiKitamura** [Epix37/Hearthstone-Deck-Tracker#2227]
Recently HDT has been failing to import cards correctly from my game. It will always put two of the cards in my deck, it will frequently use the 1 and 0 mana cards on the first page of the class instead of what I actually use in the deck, and it never imports and 2 or 3 mana cards, probably because it hits 30 cards from all the duplicates starting from the highest mana cost.

I know that this is an intended feature if your deck contains many duplicates, but I'm talking Reno Jackson/Every card is different decks. I've tried editing the log file, deleting everything in appdata, redoing the importing setup with multiple restarts before and after. Nothing seems to work.

At one point it imported a deck perfectly, but upon trying to replicate this it went right back to putting two of every card. Any help would be much appreciated.

**Comment by Epix37** [comment]
See #2179.

**Comment by tknights2015** [comment]
I am seeing something similar to this and this issue wan not present before the 4.2 HS update.
Rather than importing the entire deck and having to adjust the numbers of each card, HDT is importing cards not even in the deck and not importing all the cards.  
This is a screen shot of a imported deck and the original deck list.
![import v13 17](https://cloud.githubusercontent.com/assets/16232528/13905495/cab049ca-ee86-11e5-868b-7cd564e68640.JPG)

**Comment by YuiKitamura** [comment]
That is exactly what's happening to me, good to hear that I'm not crazy and this is actually something that isn't working as intended.

**Comment by Epix37** [comment]
Closing in favor of #2250
