### ISSUE TITLE
Exporting Decks Doesnt Work

### ISSUE THREAD

**Issue by MadMan10001** [Epix37/Hearthstone-Deck-Tracker#2245]
When I try to export decks to hearthstone as it searches for the cards to put in the deck 0 matches are found total and no cards are put in the deck. From what I can see it is entering more than just the title of the card and it may be including irrelevant information leading to an inability to insert the cards

**Comment by Epix37** [comment]
It does enter more than just the cardname, namely the artist and cost values to void running such as 'Charge' (warrior spell) also showing everything that has a 'Charge' effect. That shouldn't cause any problems however.

What version are you using? Since Hearthstone 4.2.0 you need v0.13.17 for exporting to work.

Another possibility is that is there are problem clearing the mana crystal. You can work around that by increasing the start delay under `options (advanced) > tracker > exporting` or disabling `auto clear filters`.

**Comment by ThorsAngerVaNeT** [comment]
Have problem with exporting too... HDT insert in filter field only letter "v", but when HDT "done" exporting last card name is in clipboard, I has this problem only when options > tracker > appearance > card language > primary is set to russian...
