### ISSUE TITLE
Suggestion: Deck tracker overlay positioning.

### ISSUE THREAD

**Issue by Doomelf** [Epix37/Hearthstone-Deck-Tracker#2254]
By default the overlay is set in the middle of the left and right side in Hearthstone, however, when playing with or versus decks that have 1 copy of cards (Reno decks and arena) the cards get stacked so tightly that it`s really frustrating.

I am aware there is an option to resize the overlay so that all cards can be seen normally but this requires such decks to be positioned at the top of the screen because they are so long.

It would be really nice if the overlay stayed set in the center as default and automatically resized itself by going up and down to fit the deck you are using.

This way there will be no need for shorter and more compact decks to look weird and uncomfortable starting from the top and going to the middle of the Hearthstone window.

You can see the issue by looking at the screenshots below.

![2](https://cloud.githubusercontent.com/assets/12450654/13936025/88ace040-efc3-11e5-8e3c-64598288bb6c.JPG)
![1](https://cloud.githubusercontent.com/assets/12450654/13936026/88b2a6b0-efc3-11e5-959d-8063768d91ba.JPG)

**Comment by Epix37** [comment]
Done!

I have avoided this so far because it looked awkward with cards popping in/out, for the opponent deck and when in no-deck mode or having the "remove at count 0" option enabled. 

Since that is no longer the case (the next update will have nice fading and update animations for the cards :smile:), this is a very good idea.

**Comment by Epix37** [comment]
Added with v0.14.0.
