### ISSUE TITLE
Minimize Hearthstone window after pressing End Turn button

### ISSUE THREAD

**Issue by Binori** [Epix37/Hearthstone-Deck-Tracker#2289]
Hi,

In some dangerous ;) places like school, work etc. ;) playing Hearthstone looks like that:
(1) Play cards, click end turn, click Minimize window ("hiding mode on" ;))
(2) Watching when HS windows is blinking, maximize window, go to step (1)

It would be great to have option in HDT Settings which enable auto-minimize Hearthstone window after pressing End Turn button.

Thanks for your awsome app!

**Comment by Epix37** [comment]
I don't think this is something that would fine use in too many scenarios. You can just press Win+D at the end of your turn to minimize everything.

**Comment by Binori** [comment]
Minimize all windows is very annoying when you play HS just in background. If this is too much work in your opinion then maybe you can add these kind of behaviour to Hotkeys Events? It even fit with the rest of events. 
There is already "Show main window" event to assign then maybe you could add "Minimize main window"  event? I would really appreciate this addition...

![Options](http://i.imgur.com/O6FiXhx.png)
Greetings!

**Comment by Epix37** [comment]
You could also play Hearthstone in windowed mode and press the minimize button.

I don't really see a point in adding this, sorry.

**Comment by Binori** [comment]
I don't understand why "Start Hearthstone", "Show main window", "Game Screenshot" events from Options (hotkeys) have sense for you (all of them are also build into Windows or Game) but "Minimize main window" has no sense. This is the same value as Start HS, "Show main window". You can do these events also by clicking icons.

But I respect your decision. Thank you for great app, will donate again in the future for sure. Have a nice day! :)

**Comment by Epix37** [comment]
"Show main window" does not refer to Hearthstone, it opens bring the HDT window to foreground.

My main reason for not wanting to do this is that this is a *very* specialized use case that maybe 0.01% (if that) of users will ever use. Plus there are easy workarounds for it.

Just because I have features that sort of fit the same category, doesn't necessarily mean I want to add more of those. I would much rather get rid of a lot of things, but taking features away is most of the time not very appreciated. :).
