### ISSUE TITLE
Some card marks are missing

### ISSUE THREAD

**Issue by jposuna** [Epix37/Hearthstone-Deck-Tracker#2292]
With the latest patch (0.14.0), some of the card marks are missing. I do see the coin mark, but can't see the mulligan or returned card marks (not sure about the created one... can't remember right now).

**Comment by Epix37** [comment]
I think returned currently only work for created (i.e. not drawn) cards.

Those got caught in the crossfire when trying to make sure HDT doesn't display any information leaks. 
Fixed with https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/1c4f7fc8c79e1b89a15cc51dfbd6787561cc84d3 and https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/6d24f19693faf1ba3a95e3ef306464c83ad5ebba.

**Comment by Epix37** [comment]
fixed with v0.14.1
