### ISSUE TITLE
Overlay text color problem

### ISSUE THREAD

**Issue by biglisy** [Epix37/Hearthstone-Deck-Tracker#2295]
It's been a few versions (now on 1.40) that the text of the cards which you have in hand (and no duplicate in deck) appear darkened despite being light green.

In this case, Wild Pyromancer, Justicar and the Blademaster are all darkened while they should be the same color as Flash heal (which is a duplicate, another one in deck) just with dark background.

That's how it used to work, or am I remembering wrong?

[reference picture](http://puu.sh/o23mK/076a516941.jpg)

**Comment by Epix37** [comment]
The darkening will be less opaque will the next update (https://github.com/Epix37/Hearthstone-Deck-Tracker/commit/f65247c32a96a083306ae71d636536319aab72b4). Making the green a bit more distinct. 

Have the green text darkened as well was an intended change though. It looks very out of place in the new themes otherwise.

An easy workaround you can do right now: Download [this image](https://raw.githubusercontent.com/Epix37/Hearthstone-Deck-Tracker/f65247c32a96a083306ae71d636536319aab72b4/Hearthstone%20Deck%20Tracker/Images/Themes/Bars/dark/dark.png) and use it to replace the `dark.png` in `Hearthstone Deck Tracker/Images/Themes/Bars/dark`

**Comment by Epix37** [comment]
fixed/improved with v0.14.1
