### ISSUE TITLE
Arena stats gone

### ISSUE THREAD

**Issue by cachirro** [Epix37/Hearthstone-Deck-Tracker#2305]
I have set record stats in arena and also keep stats when deleting decks, i delete all arena decks after i lose.

just went now to see stats and everything is zeroed :( not even rewards are there

**Comment by Epix37** [comment]
`keep stats when deleting decks` will keep the games under `[old] games & statistics`, however the arena statistics/runs are bound to the existence of decks. 

Rather than deleting arena decks, you can just archive them. That keeps your list clean and the decks alive.

If you recently deleted a multitude of decks, you can revert to a backup under `options (advanced) > tracker > backups`.

**Comment by cachirro** [comment]
maybe you should add a note to keep stats option saying arena is not included

**Comment by Epix37** [comment]
Added an explanation (tool tip) for what the option exactly does.
