### ISSUE TITLE
Card-mark tooltips don't work. 

### ISSUE THREAD

**Issue by LufgtHuron** [Epix37/Hearthstone-Deck-Tracker#2324]
I can't ever view the source of a card. For example: I play mechanical Yeti (or whatever it was called, the one that gives spare parts to both players) and my opponent kills it.  The expected behaviour would be to see the Yeti as a source somewhere but it's nowhere to be seen. This happens to every created/stolen card.

I don't even have the S icon that I'm supposed to. For me its either a white present (in my deck list) or a purple/violet one in my opponents hand.

Is there any fix for this or am I missing something? Im using the latest version of the tracker.

**Comment by Epix37** [comment]
The 'S' has been removed a long time ago, as were sources because they were not reliable. 
You can find [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Overlay) what is currently displayed. 

Sources will not come back, but something better will be added eventually, see https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2224.
