### ISSUE TITLE
Export to Hearthstone - Premature Stop / Failure to Execute all Card Searches

### ISSUE THREAD

**Issue by ckirkman** [Epix37/Hearthstone-Deck-Tracker#303]
When exporting a deck to Hearthstone the export *always* stops after 16-18 cards. (I've tried it with 6 decks so far.) I've deleted log files and reinstalled, have tried at different speeds, with/without prioritizing golden cards, with/without pasting from clipboard, and also setting the game quality to Low with lower resolution. (The latter shouldn't be a problem, though, as my machine is definitely overpowered for the game.)

What I've noticed when watching clicks at the slowest speed (150ms) is that some of the searches are not executed, at which point the exporter tries to click the same cards it previously had clicked. This seems to happen around every other card.

The absolute fastest speed misses even more cards (only adding 11-14, usually). But (for me) speeds between 40ms-150ms usually yield the same result. I'd like to try it on an even slower speed but I don't have Visual Studio on my machine to debug it with.

Of course, the problem might be something else entirely, but from looking at the project code and observing the clicking actions, I think this is likely related.

**Comment by MarioZG** [comment]
Just a comment that might clarify.Using  laptop that has touchscreen running win 8.1. When I try to export deck using touchscreen, i can reproduce this issue, When I use mouse to navigate in game, all works fine, It seems it's not OS related, purely touchscreen,

**Comment by roymayfield** [comment]
I posted this issue on #589.  It was indeed the Windows 8 touchscreen. +1 on comment above from mkleiman312, that fixed the problem for me. Cheers, roy

**Comment by lord666** [comment]
sorry for my english absolutely horrible, i'm a french ^^.. I do not know if it 'll help, but I had the same problem ... the software exported me 18 cards since the last update Hearthstone DECK tracker. I tried the trick 'Compatible Windows 7 " but this disables mouse clicks hearthstone -_-' it's even worse ... so I came back in" normal " mode and there .. this .. Miracle works ..I do not understand why ... but if it helps

**Comment by skaforey** [comment]
I agree, when running in compatibility mode, it does make some of the other touch screen gestures weird.  For example, to emote, you now have to long press the hero to simulate a right click.  To unselect a card to play you have to do weird things like drag the card all the way to the bottom of the screen to cancel the action.  It would be nice if there was an option that could be checked that would then make the exporting function properly without having to use compatibility mode (you just have to click on one area, then click to another area).  I might have a go at coding a fix since I can reproduce the issue quite easily.

**Comment by ynet2k** [comment]
It was indeed a problem caused by the touchscreen mode. Just wanted to confirm this.
Thank you!

**Comment by ekyriakides** [comment]
Is there an alternative workaround for this? Or has there been a fix since?

I tried to use HDT on my Surface Pro 4, and since I play purely on touch; changing it to Windows 7 compat mode seems to break alot of the touch controls.

**Comment by Epix37** [comment]
Potentionally "fixed" with the `Force clear searchbox between cards` option (`options > tracker > exporting`) added with v0.13.8?
