### ISSUE TITLE
Automatic deck detection with deck not in HDT still selects a deck when it shouldn't

### ISSUE THREAD

**Issue by Fyren** [Epix37/Hearthstone-Deck-Tracker#367]
If I play a deck that I don't have set up in HDT, but I have automatic deck detection on, it often picks a deck of the same class even if it can't be the right deck based on the cards seen.  For example, I usually don't add arena decks since that's a hassle.  But when I play arena, it usually picks a deck even though started out with cards that aren't in the deck it selects.  I have to tell it to use no deck.

**Comment by Thristle** [comment]
I guess you *could* add a limit to how different the decks are and then use no deck but it would require trial and error

**Comment by Fyren** [comment]
There would necessarily have to be a fuzzy limit, just an option to use no deck if no existing deck matches the current deck.  It might be a little weird if HDT can't realize till mid-game that the deck doesn't match any.

**Comment by Epix37** [comment]
This happens because before any cards are drawn, as soon as your current class is detected, HDT switches to the last deck played with that class. Most of the time this will be the correct pick. 

I don't really want to add automatic switching between "deck" and "no deck" mode if I can avoid it. I'm not really sure how pressing this issue is anymore either since importing arena decks from the game is a very quick thing to do now. Also *if* you want to switch modes, you are probably not switching between the two at a frequency where it's too much to ask to manually activate either.

What I did add now though is a warning when no matching deck could be found.

![screenshot 2015-04-03 15 33 08](https://cloud.githubusercontent.com/assets/7737910/6982927/2156e5c4-da18-11e4-8f88-c7f237c42faf.png)
