### ISSUE TITLE
Zero Turns Bug

### ISSUE THREAD

**Issue by Bahzur** [Epix37/Hearthstone-Deck-Tracker#549]
So, i was just playing some matches in a row with the same deck, when suddenly in a match against a handlock the stats for that match weren't recorded. I immediately looked at the log and noticed 2 weird things:
-The match was discarded cause the tracker thought there were zero turns, although there were clearly many turns (i enabled "discard games with zero turns")
-The opponent cardcounter marked all cards (except the coin) with 0K, as if he was still in the mulligan phase
Thinking about the match, i noticed that all cards were already marked that way the whole match ingame, but didnt think much about that at that point. Heres the log:
http://pastebin.com/gNzQ2SrS
The match in question is the last one, just scroll completly down.

**Comment by Epix37** [comment]
Second report in this direction. There seems to be a an issue with clearing the log file. Apparently it sometimes gets cleared after the game started.

**Comment by Bahzur** [comment]
Good to know, thx for telling. Ill disable discarding zero turn games for now, just in case.

**Comment by Epix37** [comment]
Oh it might not be a log file issues after all. 

In 0.7.3 the tracker returns 0 as turn number if the mulligan is not yet over. That check uses fixed indices in the entities for the player and opponent. If some some reason the indices are different *this* will happen. 

That behaviour was also causing other problem and is already fixed with 175e49e. So I'm pretty positive this is fixed as well.

**Comment by Bahzur** [comment]
Horay! :D 
Great work dude!

**Comment by Epix37** [comment]
should be fixed with v0.7.4
