### ISSUE TITLE
warlock hero power throws off turn drawn counter

### ISSUE THREAD

**Issue by Jinjubei** [Epix37/Hearthstone-Deck-Tracker#606]
http://gyazo.com/7f8cddd4fc0c5b99d63d3c50e7509cac

**Comment by Elitesparkle** [comment]
Did you play that game from the beginning up to the moment you took the screenshot?
I ask it because those numbers will always mess up when reconnecting to a previous game for how they are handled by the game itself.

@Epix37, maybe they changed something about this after Goblins vs Gnomes came out. I've noticed that sometimes I see my opponent's name even after a disconnection. Check it.
If that's true, there is a chance to fix this issue, even if it isn't what he was trying to say, maybe.

**Comment by Epix37** [comment]
As the number of cards is correct, I would guess here (as I did in #610) that there are currently issues with the logs due to (server) issues on blizzards end.

**Comment by Jinjubei** [comment]
@Elitesparkle I did play the game the whole way through once the warlock used his hero power the card count began to get wonky and after a few more turns I took the screenshot to try and demonstarte the issue better.

**Comment by Epix37** [comment]
Does it happen every time you play against a warlock?
