### ISSUE TITLE
Suggestion: Add Decks'name in the Overall Stats 

### ISSUE THREAD

**Issue by Calioe** [Epix37/Hearthstone-Deck-Tracker#695]
![capture](https://cloud.githubusercontent.com/assets/7279626/6199778/11d596de-b459-11e4-9a56-2749f62322fe.JPG)
 Obviously it will be very usefull as it is difficult to see in one time all the information on this view....;)

Thanks!

**Comment by GiggliG** [comment]
I would like to see the deck's name, too, but I don't think that screen has enough room for it.
My suggestion is to make it a hovertext, so when you hover the mouse over a deck, you see the deck name floating above it.
I also submitted a request so that when you click on a game, it changes the active deck to the deck used in that game. Someone else suggested adding a button to do that. Either approach would be good.

**Comment by GiggliG** [comment]
Another thought:
that list could have a right-click menu for some obscure options, leaving the row of buttons at the bottom for the most well-used functions.
