### ISSUE TITLE
Cleaner options menu

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#738]
I finally got around to cleaning up the options a bit. Or at least be basis for it.

I am still unhappy with the structure. Things like `general > other` are just a messy assortment of stuff and I'm not sure what to do about it.

If anyone has ideas on how to better structure the whole thing, please share them with me!

The new menu:
![screenshot 2015-03-02 17 48 48](https://cloud.githubusercontent.com/assets/7737910/6445471/63ef08ee-c104-11e4-9c76-a01d721cca8d.png)
[(branch)](https://github.com/Epix37/Hearthstone-Deck-Tracker/tree/options-remake)

**Comment by GiggliG** [comment]
Some of the organisation seems a bit iffy.
In the old options section, the heading Decks contains things which are all about the overlay.
So I'd change the section you have above that goes like this:
Decks 
-- General
-- Opponent

To:

Overlay
- General (the stuff that's currently in General-> Overlay)
- Additional Windows
- Player
- Opponent
- Other (see below)

Most of the options in General -> Other are also about the overlay, and should be moved to the Other tab suggested above. 
The option seettings "Full text in new deck, card tool tips in tracker, show deck stats in new window, keep stats when deleting deck" should be moved to a section of their own.

I'd replace the General and Other sections with something like:
Tracker 
- General (put whats currently in Other/Tracker)
- Record Games
- Export
- Import
- Settings (those settings I mentioned above could be moved here)
- Logging

I think that covers everything.

**Comment by britishben** [comment]
For the overlay menu, It'd be nice to see what the screen would look like with each change to the options (have a mocked up screenshot with the changes as options are selected). Maybe change the wording to "Show:" rather than hiding, to match the style of the "Decks" menus.

I'd move the "Decks" tab stuff into the overlay as well, it's not immediately obvious that they're related. Maybe just make the "Overlay" the tab, as GiggliG suggested above, and then have a "Decklist" sub-category.

For a bunch of the options, try to avoid repeated words. That makes the options seem way more complicated than they are. Change: "Record Ranked", "Record Arena", "Record Casual", etc. to a bit of text that says "Record the following game types:", with the checklists saying "Ranked", "Arena", "Casual", etc. The "Other/Tracker" menu is way cluttered, break off stuff like "AppData" and "Launch options".

**Comment by Epix37** [comment]
Changes based on your suggestions: http://imgur.com/a/ObJcJ

Thoughts?

**Comment by GiggliG** [comment]
It looks good, but I can see room for clearer organisation.

The Overlay -> General menu could be called Overlay --> Display.

Looking at the Tracker section, I see two different groups. One group which deals with tracking a game as its played, and one which deals with management of decks outside of games.

Tracking (note the word change to distinguish from the program name)
- General (everything in the Tracker General tab that's above the line
- Stats

Decks
- General (the stuff from the Tracking -> General tab, below the line)
- Exporting
- Importing

Application
- Settings (the stuff from Tracker -> Settings). This could be divided over 2-3 tabs - Theme, Settings, Paths.
Also, the "advanced window search" setting here could be moved up to Decks -> General.

What do you think?

**Comment by Epix37** [comment]
I'm a bit on the fence. I sort of agree, but at the same time, I like the Overlay - Tracker split a lot (so I'm gonna argue for that now :)). It's simple and perfectly represents the two "parts" of the application. I would probably consider this a bit less "intimidating" for new users.

Splitting Tracker:General in two would mean splitting Tracker:Stats as well. The same applies there. All in all, that would be 18 items on the left, instead of the current 12. Making things actually harder to find, rather than easier? With lots of things being called basically the same just under a different title. 

I can't quite see "advanced window search" belonging in general. It simply determines if the hearthstone window has to be called "Hearthstone" (not the case in e.g. chinese) or if it can be any unity window. 99% of users will never touch that.

**Comment by GiggliG** [comment]
I do agree the current division is simple, but I don't think it's logical because: When i saw what was in the Tracker-> General section i did kind of a doubletake, and thought it should be under Overlay. That's because I was thinking of the two divisions being: Overlay = "while hearthstone is in use", Tracker = "while using deck tracker, but not hearthstone". That's a logical division, but the two categories don't quite fit that division.

Currently Overlay has everything to do with overlay, but Tracker is basically a grab bag of "everything else, including some things that kind of fit being in Overlay if you think of Overlay as what you see when playing games in Hearthstone."

Having 18 things might not be harder than 12, if they are grouped logically and understandably. People (well, this person) look at the group names first, then the subgroups. 

I wouldn't agree that the stats section needs splitting up - maybe just rename it to Games. (Could do that anyway, it might make more sense even in your original presentation.)

Lastly, my suggestion for breaking Settings into 3 may well be overkill and if you didn't do that, and just had a single Settings tab, there's not many more entries than your current layout. Most of the extras are just extra group names, and if they help people find what they are looking for, it's a plus not a negative.

I did misunderstand what advanced window search was, so you're right, it does belong where it is.

Anyway, thank you for entertaining my suggestions. Whatever you do will be fine, I'm sure.

**Comment by Epix37** [comment]
Released as-is with v0.9.7, will still see more improvement with the next update(s).
