### ISSUE TITLE
sync between 2 computers doesn't work, the cards are not updated on the second computer

### ISSUE THREAD

**Issue by jeantend** [Epix37/Hearthstone-Deck-Tracker#742]
I change the cards and the version on computer 1
The auto sync updates the deck on hearthstats
On the second computer, sync doesnt do anything
Full sync update the version (the deck show the new version), but nothing else : on comp 2, the name is not updated, the card list is not updated (I think notes are also not sync)

**Comment by YvesW** [comment]
Happens to me as well; I always need to delete playerdecks.xml and then force a full sync.

**Comment by caldwelljt2** [comment]
I've given up on syncing them, it keeps fouling up and I don't catch it in time before its screwed up my other data. My only solution so far has been to playing all my ranked games on one computer, so when it matters then I know I'm working with valid data. :-P

The best option I've had was where I did some fancy footwork with network sharing, but I found that I forgot and left the tracker running one place or the other, and two of them running and having them save to the same location created other issues. (That and since the android version came out I found I was already loosing 'some' information, so it wasn't 100% accurate anyways.) So if I couldn't get 100% accurate all the time, I just focused on getting 100% accurate when it matters.

**Comment by GiggliG** [comment]
There's a setting, "Close with Hearthstone" in Options --> Other. If you check that, whenever you close hearthstone, HDT will close, too, which could help you.

**Comment by Epix37** [comment]
I will have a closer look at this next week.

**Comment by FenrisWolffe** [comment]
This is still the #1 feature I desire most. I've tried about 4 different methods, and none of them have worked.

I can now get it to update with full sync so at least the decks are all the same, but even a full sync will NOT copy the win-lose % rates and such so that I have an accurate reading.

Also, this is just me, but... if you put up a patreon or paypal, I'd gladly donate to help out. I know you bust your ASS on this free software, and we non-coding users can be a demanding (and often thankless) bunch. If that info is already here somewhere, please point me to it, so I can at least buy you a cup of coffee or a sammich.

**Comment by Epix37** [comment]
That "next week" thing was about accurate I see. 

This is still on my todo list!

(there is a "donate" button in the titlebar of the app ;))

**Comment by FenrisWolffe** [comment]
James, your donation is now completePayment by PayPal
Confirmation number: 6CY27191C42403923.
Donations Coordinator Contact Information
epikz37@gmail.com

Sooo. About that feature? *ducks and runs*

**Comment by Epix37** [comment]
Thank you!

As I said, still on my todo list. Can't really say when I get around to it though. (Or how long it takes to fix it)

**Comment by Epix37** [comment]
Found and fixed this.

**Comment by jeantend** [comment]
Currently I'm using V0.9.10 and it doesn't works
I'm made some updates last evening on my computer 1.I check on hearthstats  online, the deck is updated.
This morning on the second computer, I open HDT the deck is not updated. Try sync and full sync, but the cards doesnt update.

I always have to delete PlayerDecks.xml and full sync.

Regards,
Jean

**Comment by culinko** [comment]
The fix is not released yet.

**Comment by Epix37** [comment]
*Now* it is!

**Comment by jeantend** [comment]
hello,
Now I use V 0.10.0 
Made some updates yesterday on computer 1.
Look like the modification on existing deck hasn't been sent online. The version has been added online, but the cards have not change :(
When I launch computer 2, with normal sync the new version has not update. With full sync, the version has updated (but of course not the cards because they have not been updated online)

I also made a new deck, this one has been send online and updated on computer 2 with normal sync.

**Comment by jeantend** [comment]
Made a test this evening on my computer 1 
With Force full sync : the deck list is updated online.

Strange that the normal sync doesnt update the list online. Is it the way you want it to work ? Looks more like a bug I think.
I will test tomorow if the normal sync download the updated list or if I also have to force full sync.

Do you want me to create the bug repport on the V 0.10.0 version ?

Regards,

**Comment by jeantend** [comment]
Hmm made an other update on an other deck, and the deck liste and name has been updated with auto normal sync.

Realy strange

**Comment by Epix37** [comment]
Very strange indeed. Might be an issue with some old decks worth versions. 

A deck being archived on hearthstats should not affect syncing.
