### ISSUE TITLE
Importing constructed decks from the game

### ISSUE THREAD

**Issue by Epix37** [Epix37/Hearthstone-Deck-Tracker#762]
This is exciting!

I found a way to make importing of constructed decks work the same way it works with arena!

I would appreciate some testing on this.

As always with test releases: **Please back up your "%AppData%/HearthstoneDeckTracker" (Win+R, paste) folder, just in case**
Download: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE5

![screenshot 2015-03-08 11 13 59](https://cloud.githubusercontent.com/assets/7737910/6545449/67fc0472-c588-11e4-9772-fe3be488c2db.png)

**Comment by dvide** [comment]
It worked nicely first time I tried it with a druid deck, though I didn't save the deck. Then I deleted the deck in hearthstone and tried a hunter deck but it always just imports 6 cards from the druid deck.

**Comment by Epix37** [comment]
Did you go back to the main menu before importing again?

**Comment by dvide** [comment]
Yeah. Tried closing down hearthstone and reopening and it seems to work again.

**Comment by Epix37** [comment]
Just tried exactly that, worked fine for me. One way of probably preventing that would be to have the user specify what class the deck will be `Import from game: constructed > [Druid, Hunter, ...]`. I would prefer to avoid doing that though.

**Comment by dvide** [comment]
It's weird, sometimes it works but most of the time I just get those 6 druid cards still. Can't figure out what I'm doing right when it works. Only had it work properly twice I think.

**Comment by Epix37** [comment]
I made a change to the class detection: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE4

Do you still have the issue with that?

**Comment by Epix37** [comment]
Oh, any chance your deck consisted of only or mostly neutral cards?

**Comment by dvide** [comment]
Still happens with 0.9.7PRE4. Yeah mostly neutrals, let the game fill the deck out for me.

**Comment by Epix37** [comment]
The easiest way of figuring out what's going on would probably be for you to debug through [HandlePossibleConstructedCard](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/d11de8d051c7e15fbcb517eafd8ca0ecd65409ae/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L525) and [BtnConstructed_Click](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/d11de8d051c7e15fbcb517eafd8ca0ecd65409ae/Hearthstone%20Deck%20Tracker/MainWindow/MainWindow_Import.cs#L330).

**Comment by dvide** [comment]
I'll try that in a bit, see if I can figure out what's happening. I'm just going for a run now but I'll come back in about half an hour.

**Comment by Epix37** [comment]
Brief explanation of how the whole thing works: 

On exiting the collection screen all cards get unloaded, including the cards in the book on the left. Those are unloaded last though and can be [easily filtered out by manacost](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/d11de8d051c7e15fbcb517eafd8ca0ecd65409ae/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L534). 

Problem: these may include low cost cards that are actually in the deck.
Solution: [there's also a "card was already in cache" message, that fires when the deck opens](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/HsLogReader.cs#L486) (arcane shot was on the left in the book, and is now also found in the deck). 

The list of "possible constructed cards" then contains (or should contain) 4-8 druid cards (those on the first page, no way around that) plus all the cards found in the deck.

Edit: I found the issue but since I wrote this already, might aswell post it :). The part that filters out cards would kick in after the druid cards in some case. This now ignores the first 8 cards. 

Build: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE5

**Comment by dvide** [comment]
0.9.7 works a lot better now :)

**Comment by dvide** [comment]
"On exiting the collection screen all cards get unloaded, including the cards in the book on the left. Those are unloaded last though and can be easily filtered out by manacost."

If you type some random thing in the search field so that no cards appear in the book, would that help so that only the cards in the actual deck are unloaded when you close the deck screen? Or could you start counting the cards that get unloaded from that point on? Maybe this whole thing could be automated with virtual clicks, like with deck exporting.

Not taken a deep look at it yet, so my thoughts might be nonsense.

**Comment by Epix37** [comment]
Wouldn't work. The cards are already loaded at that point and will therefore be unloaded when exiting the collection screen. Search filter resets when exiting so that won't work either. 

Maybe there's *some* way, but I don't see it. Doesn't really matter either way though since this seems to work now. 

Problem with automating is that you need to select which deck to import and have to start from the menu to make sure the user didn't open other decks before. (On that note: I have a local branch where I started working on starting the exporting process from any screen though :))

**Comment by dvide** [comment]
That's a shame. The cards aren't unloaded when you actually perform the search then? Just when you exit the screen? I see.

Maybe you could do Import -> Deck Slot 1-9 submenu. Not sure if the deckslots would be in consistent positions though on all resolutions.

My zoolock deck always has a sacrificial pact when it's not in the deck. And a druid deck I have doesn't include Innervate when it does have it. So it's not quite right yet unfortunately.

![hearthstone_screenshot_3 8 2015 11 59 50](https://cloud.githubusercontent.com/assets/180188/6545742/102ab328-c58e-11e4-8cf7-929735b53dbb.png)
![hearthstone_screenshot_3 8 2015 12 00 07](https://cloud.githubusercontent.com/assets/180188/6545743/102df0b0-c58e-11e4-88a8-0e0b8e34b6f3.png)

**Comment by Epix37** [comment]
The problems seem to be related to golden versions of the card. I'll try to figure that out.

**Comment by dvide** [comment]
Figured it was probably that. Hope there's a solution.

**Comment by GiggliG** [comment]
I gave this try with this deck:
![hdt_warlock2](https://cloud.githubusercontent.com/assets/10089419/6546655/9733ecd4-c5b3-11e4-99b3-40d356356210.jpg)

Here's what got imported.
![hdt_warlock1](https://cloud.githubusercontent.com/assets/10089419/6546654/973329d4-c5b3-11e4-8717-a9b122e2feb1.jpg)

**Comment by GiggliG** [comment]
If this feature does prove reliable, one great feature would be to import to an already existing deck as an extra version.
I think the most common way people will use this is, they'll take a deck they have in both HDT and hearthstone, modify it in hearthstone, and then export it to HDT and want the original deck there updated with the tweaks.

**Comment by Epix37** [comment]
Should work a lot better now: https://github.com/Epix37/HDT-Test/releases/tag/v0.9.7PRE6

What you have to do: run "set up constructed importing" in options > tracker > importing once. That usually shows up with the explanation when clicking the import menu item for the first time but you probably did that already.

I will add a way to import new versions using this once it's working well enough.

A few cards from the first page of a class might still be missing here or there but for the most part my testing seemed pretty good. Innervate is stubborn for some reason, no idea what's up with that.

**Comment by dvide** [comment]
Seems to be working well for me, from a limited test. Still misses innervate like you said, and sometimes it misses random cards (missed an explosive sheep and mad scientist, but then I tried again and it worked that time), but the sacrificial pact doesn't show up anymore :)

**Comment by dvide** [comment]
In fact it misses any card that's on that first druid page.

**Comment by dvide** [comment]
Actually it seems that it never includes cards that are on the class's first page that I don't have a golden version of. If I have a golden version of the card, it won't miss it (whether I put the golden or non-golden one in my deck).

**Comment by dvide** [comment]
Very strange, what I said above only seems to apply from Hunter to Paladin. From Priest onwards it works fine, so even if I don't have a golden version of the card it will pick it up. But with Hunter, Mage, and Paladin, it only picks up those cards on the first page when I own a golden version of them.

**Comment by dvide** [comment]
Hm it's working now, and I think it was failing before because `Helper.SettingUpConstructedImporting` got stuck on true somehow, even though I wasn't doing the 'setting up' process at the time. Not sure why it was true, but when debugging I noticed that it was and I think that explains why it would only add cards where I had a golden version. Now that I've reset that variable it appears to be working as expected. So all of the above was kind of a non-issue I think.

**Comment by GiggliG** [comment]
I've tried this with one deck, and had the same issue with my earlier post. The exported deck had mostly cards that weren't in the deck i created.

**Comment by Epix37** [comment]
That's weird. Same issue with all classes / decks? 

Maybe it's just the way you phared it, but you have to go back to the main menu after creating a deck, before importing. Importing must only consist of "menu, collection, deck, back, back, import".

If that doesn't work maybe try running the setup again, then restart hdt.

**Comment by dvide** [comment]
I think I've figured out what's causing the issues with Druid.

I think what happens when you open a Shaman deck, for example, is that it loads the shaman cards first from the deck, then it loads the Shaman first page in the card collection book. Any cards that have already been loaded into the decklist that are also on the first page of the Shaman book cause the AlreadyInCache message. But it doesn't work the other way around, where it would fire the AlreadyInCache message when the cards being loaded in the decklist match cards that have already been loaded in the book.

So for example, with this Shaman:
![hearthstone_screenshot_3 12 2015 13 05 43](https://cloud.githubusercontent.com/assets/180188/6618184/b6ca7c5e-c8b8-11e4-8f93-81b56869cd8e.png)

If I open up the card collection and then immediately go to the Shaman first page, without opening the deck, I get 1 AlreadyInCache message for the ancestral healing. Then when I open up the deck, I get 1 AlreadyInCache message for the golden feral spirit, but I don't get any AlreadyInCache messages for the Lightning bolt and Rockbiter weapons.

If, however, I open up the card collection from scratch and then immediately open the Shaman deck, I do get the AlreadyInCache message for Lightning bolt and Rockbiter weapon, but that's because it must have loaded the deck first and then it opens up the first page of the Shaman book, and it's that which is firing the messages.

So with druid, you cannot avoid loading the Druid first page immediately before you load a Druid deck, and so if a Druid deck contains innervate, or anything from that first page, it doesn't fire the AlreadyInCache message when the Druid deck is loaded. I'm not sure if there's a solution to that :(

**Comment by dvide** [comment]
I also think the statement [here](https://github.com/Epix37/Hearthstone-Deck-Tracker/blob/cbc36a1b774b3560c45a1ba4dd752a5ef3b24ae1/Hearthstone%20Deck%20Tracker/GameEventHandler.cs#L557) needs to be changed to:
`var containsOtherThanDruid = Game.PossibleConstructedCards.Any(c => c.GetPlayerClass != "Druid");`

`Card.PlayerClass` is null when the card is a neutral, but `Card.GetPlayerClass` returns 'Netural' if `Card.PlayerClass` is null.

**Comment by Epix37** [comment]
I agree, there might not be a solution to the druid issue. Though adding a few cards manually is not really the end of the world. 

> So !string.IsNullOrEmpty(c.PlayerClass) && c.PlayerClass != "Druid" returns false when the card is a neutral, which I think is not what you intended.

That actually is what I intended. I want to know if the deck contains any non-druid class cards. And if so, the druid cards can (and must) be ignored in the following count because a deck of another class was opened. The reason for the count check is that cards sometime get added out of order. I don't remember why but I had e.g. abusive sergeant as 8th or 9th unloaded card, causing `_doneImportingConstructed` to be set to true.

**Comment by dvide** [comment]
Oh right, I see. My bad. So why the `cardCount > 10`? Why did you choose 10 I mean? Just a sufficiently large number? I was trying to figure that out earlier. Meant to ask.

Do you have a golden Abusive Sergeant btw? Just noticed that the golden Feral Spirit I have in that Shaman deck is unloaded last (after Fire Elemental but before Ancestral Healing in the book).

**Comment by Epix37** [comment]
Just a sufficiently large number, yea. The issue was abusive sergant at 8 or 9, must be less than 15 (when each card x2). Maybe 11 is better, don't know. 10 seems to work though.

I do not have a golden abusive sergeant, no.

**Comment by Epix37** [comment]
released as "beta" with 0.9.7. 

I love how you can just slap "beta" on things nowadays and people are totally ok with it if things don't quite work. :).

**Comment by GiggliG** [comment]
If you're an AAA games publisher, you don't even need to slap beta on it :)

**Comment by Epix37** [comment]
Improved the behaviour of this and arena importing a bit with c42889f: Both items are always enabled and will show the instruction dialog if not enough cards were detected yet.

**Comment by fref** [comment]
I haven't been able to import my almost-basic-only mage deck so far. I'll try again, but I'm pretty sure I follow all the right steps.
