### ISSUE TITLE
Suggestion: Edit Name without Editing deck

### ISSUE THREAD

**Issue by GiggliG** [Epix37/Hearthstone-Deck-Tracker#784]
Now that we have versioning, it makes less sense to have to open the edit deck screen if we just want to change the name of a deck. Could you add a feature just to edit the name?

**Comment by Epix37** [comment]
Technically that would obviously be no problem and I wouldn't mind adding it but I'm interested in why. Is would require the same amount of clicks as it does currently. All loading times would be similar. 

Should the edit panel be better organized? Is the name textfield too small? What's the main reason for not wanting to use the normal edit?

**Comment by dantedog** [comment]
For me, it is that the edit panel is larger than the standard window. If I click edit, the size of the tracker almost doubles in size. This often leads to having move the window as it will be partly of the screen. It also require you 'refocus' your vision and find the deck name. You also have to move your mouse a fair distance to click the save button. 

Its all really tiny stuff that doesn't matter, but it does lead to a (very) slightly diminished user experience.

**Comment by Epix37** [comment]
The window now automatically moved to the left if opening edit causes it to go outside the screen. 

As for the name editing, is this along the lines of what you had in mind?
![image](https://cloud.githubusercontent.com/assets/7737910/6646995/7fc9fc12-c9ca-11e4-8a6f-98dd69469bc7.png)
![image](https://cloud.githubusercontent.com/assets/7737910/6646992/7b1110a2-c9ca-11e4-9d10-6201c06a53b7.png)

**Comment by dvide** [comment]
I've changed it so that it restores the original window position on edit panel close, or if the application is shut down when the edit panel is open. This isn't done if the user moves the window in the meantime, however.

This way, if users like to keep their HDT on the right side of the screen in a consistent position, hopefully they won't have to move it around ever.

**Comment by Epix37** [comment]
Ah perfect, thanks.

**Comment by dvide** [comment]
Now also shifts left when you keep the window on the right side of the left screen, or any screen, not just the rightmost screen. It's smart about it though, so if the right side of the original window is slightly overlapping onto the right screen it will still shift left, but if it was mostly on the right screen it will not. This way, if the user keeps HDT on the left side of the right screen, it won't shift left if you accidentally leave it a pixel or two overlapping onto the left screen (if that makes sense).

It also fully aligns the window to the right side of the screen instead if the moving it would leave more than 50px between the right side of the window and the right of the screen. This way, if the window is already closer to the middle of your screen but the new width would cause it to move, it will just fill the space rather than leaving a big gap.

**Comment by GiggliG** [comment]
Yes, Epix, that screenshot is exactly what I had in mind.
You asked why: When I change the name, I'm always a little wary of accidentally incrementing the version number.  It does seem overkill to open the entire edit deck window just to change the name too,
