### ISSUE TITLE
Suggestion: display period

### ISSUE THREAD

**Issue by Elitesparkle** [Epix37/Hearthstone-Deck-Tracker#790]
I see a new section in the Options: Tracker > Stats > Display.

Can you add Period to filter the stats that are shown on the overlay?

**Comment by GiggliG** [comment]
I like that idea, too.

**Comment by Epix37** [comment]
Does anything other than `All` and `Current Season` make much sense here? `Today` maybe. 
Stuff like `Last week` is probably not necessary.

Given the stats screen will get an overhaul at some point.

**Comment by GiggliG** [comment]
All, Current Season, This Week, and Today make sense to me. I agree that Previous periods don't make sense for this area.
"Since Last Expansion" could make sense too, or being able to set a specific start date ("From:" <select date>) in Options, though i could see why you might think those are going too far.

**Comment by Epix37** [comment]
![screenshot 2015-03-15 12 28 16](https://cloud.githubusercontent.com/assets/7737910/6655810/693cc4d4-cb0f-11e4-9574-c12a85624d43.png)
![screenshot 2015-03-15 12 28 21](https://cloud.githubusercontent.com/assets/7737910/6655811/6a448718-cb0f-11e4-900d-fe5d21ba9a43.png)

The date picker is german on my system for some reason, even though nothing else is. Will be the appropriate language on other systems though.

**Comment by Elitesparkle** [comment]
Nice.

**Comment by GiggliG** [comment]
Excellent.
