### ISSUE TITLE
In regard of "How to start Hearthstone-Deck-Tracker with the launcher?"   

### ISSUE THREAD

**Issue by pefp2008** [Epix37/Hearthstone-Deck-Tracker#798]
I know how to Create the .bat file.
Just some questions to clarify:
-if i have installed HS and HSDT in different folders, in relation to the folders noted in the code, do i need to change them as well? (should be put as a note)
-After the .bat file is created, where should i keep it? (should be put as a note)
-After the first launch (with the .bat file), is it necessary to click-on the file everty time i start HS? (should be put as a note).

In other matters, nice app. Its very useful, and works pretty well

**Comment by GiggliG** [comment]
I'm not 100% sure of what you mean by your first question, but the BAT file should contain the full path to your HS exe and the HDT exe.

After the bat file is created, if you have used full paths for the above addresses, you can put it anyway. You can create a shortcut to the bat and add that shortcut to your taskbar or start menu.

For you last question, the answer is yes IF you have HDT set up to shut down with HS (it's a setting in the options). Otherwise, no you dont have to. but if you create a shortcut to the bat and put it somewhere convenient like your taskbar, you might as well.
