### ISSUE TITLE
Suggestion: Language support

### ISSUE THREAD

**Issue by Paradowski** [Epix37/Hearthstone-Deck-Tracker#818]
I would like to add a new language support system so the other developers could easily add the full translations of this app in their native languages without bothering with the rest of the app's source code(i.e. by adding some data to specially created class). I think I can create the fully operative code in the next 1-2 months.

**Comment by Epix37** [comment]
See #471.

This is something I still plan on adding at some point and want in for the "1.0" release (whenever that's gonna be). So far it got delayed due to designtime exceptions using wpflocalizeextension and just my desire to constantly change the GUI. Having to change in over a dozen languages every time would make that quite hard.

**Comment by Paradowski** [comment]
As I can see in  #471 , I can help with translating to Polish (plPL) ;)
