### ISSUE TITLE
The Tracker Stops Tracking my Opponent

### ISSUE THREAD

**Issue by 5th-Amendment** [Epix37/Hearthstone-Deck-Tracker#819]
To me, the tracker has only ever done this once.
![hearthbug](https://cloud.githubusercontent.com/assets/1873994/6771885/87f343d0-d0aa-11e4-8976-0120b8231568.jpg)
While the tracker counts which cards my opponent has played, my opponent's timer is always zero, so the timer goes into a constant 90 second cycle, completely disregarding the ending of turns. In other words, the snapshot shows a match that has gone on for 4 minutes and 52 seconds. Then, the counters on my opponent's hand either shows 0 with K or -1.

**Comment by Epix37** [comment]
I would guess this is some log issue. Probably not worth investing time into unless it keeps happening.

**Comment by NightKev** [comment]
It's happened to me somewhat often (one in every 10-15 games maybe?). I'll grab the relevant files if it happens again ("discard 0 turn games" was enabled prior to now).

**Comment by NightKev** [comment]
Actually, where ARE the relevant files stored?

**Comment by culinko** [comment]
in C:/Users/.../AppData/Roaming/Hearthstone Deck Tracker

**Comment by NightKev** [comment]
Well, I found the replay file but I have no idea which log corresponds to it because they're all named based on the GUID/UUID/whatever of the game. Here's the replay file: https://dl.dropboxusercontent.com/u/2674926/NightKev%28Rogue%29%20vs%20UNKNOWN%20HUMAN%20PLAYER%28Paladin%29%201624-220415.hdtreplay
