### ISSUE TITLE
[v0.10.0_PRE3] Gang Up cards mess up deck detection

### ISSUE THREAD

**Issue by ToonBoon** [Epix37/Hearthstone-Deck-Tracker#877]
Running the prerelease I get a deck mismatch becasue of the cards that Gang Up adds to the deck.

**Comment by Epix37** [comment]
Yup, I'm aware. Not really sure how to solve that yet.

**Comment by ToonBoon** [comment]
I'm thinking something like adding a flag to Gang Up copies that causes
them to get ignored in the deck matching portion.

I also think this requires all 3 drawn copies of X to look for a Gang Up
copy of X before looking for a regular copy of X again. Not too sure on
this last bit, needs thinking about possible scenarios.

**Comment by Epix37** [comment]
Problem is, draws currently only look at the card Id, not the entity Id. So "tagging" them doesn't really work because the cards drawn is another instance of a card than the one added to the deck. Before brm this was fine. 

I may just have to keep track of entity id's all together. Most future proof I guess.

**Comment by Epix37** [comment]
Try this: https://github.com/Epix37/HDT-Test/releases/tag/v0.10_PRE5
I played a few mill rogues games now, both sides going to fatigue, no warnings.
