### ISSUE TITLE
Deck Stats: Colours don't reflect actual options selected

### ISSUE THREAD

**Issue by kevorkien** [Epix37/Hearthstone-Deck-Tracker#880]
Of course this just may be a personal opinion thing, but ---- every ---- single ----- time ---- I'm on the stats page and trying to find games and go to flick my mouse up to one of the four main options (Deck, Overall, Stats or Games) I reach for the one that looks "greyed out".

Intuitively that's the way I guess programmes normally behave to me. I don't play Hearthstone a lot, kind of off and on during the week, so I'm coming at this from an angle I think most users would, as opposed to someone who has used the programme frequently.

To me it just feels like the ones with the colours that stand out the most are the ones you currently have selected. It's weird, if they were actual buttons designed to have a 3D looking texture for example, I would feel they should be the other way round though.

Just my 2 cents though :)

**Comment by Epix37** [comment]
I don't have the app in front of me right now so I'm not 100% sure what way around the coloring is. For now this must do though because it's just the way the tabs work by default. 

I plan on redoing the stats screen soon anyway (which is why I don't want to invest any time into this at the moment), probably similar in design to the deck picker. Should hopefully make things a bit clearer.

**Comment by kevorkien** [comment]
Thanks for the speedy reply. And I completely agree and understand with where you're coming from. The program is amazing as is and moving forward in leaps and bounds, this issue (if it IS an issue anyone but me is having ;p) is fairly trivial in nature and by comparison.

Regards.
PS thanks for all the hard work yourself and others have put into this.
