### ISSUE TITLE
Reconnected games don't update the statistics

### ISSUE THREAD

**Issue by fmoraes74** [Epix37/Hearthstone-Deck-Tracker#922]
I was playing arena today and I got disconnected from Wifi briefly. The game reconnected and I was able to finish the game. I lost it and had to restart HS to start a new game, but the loss (or win) is not recorded for the deck, which kept showing the old record.

**Comment by culinko** [comment]
Same as #299.

**Comment by mvordeme** [comment]
That one has been closed. Does it mean it can't be fixed? I lose quite a number of replays due to DSL reconnects.

**Comment by culinko** [comment]
I'm pretty sure that something about it can be fixed, the only incorrect thing would remain the number of turns and no/incomplete replay. But I believe it's much better than missing a complete match. I don't know why the initial report has been closed, though.

**Comment by culinko** [comment]
So, I found out that Hearthstone log shows you even the turn numbers (I reconnected at "TAG_CHANGE Entity=GameEntity tag=TURN value=7" and the game ended on value=17). Because the tracker knows what turn value to assign if match ends with the value 17 (I believe it's 8, because full 8 turns took play), you should be able to recollect all of the needed info for a full game entry.

So, the tracker just needs to join the starting info that took place before disconnect and reconnect (start time, coin) with the ending info (end time, result, conceded, turns, + other like rank). I don't know when it gets nicknames, region, mode, deck and other stuff, but all should be there in the log (even in HDT log itself).

The replay and game files would still be incomplete/corrupted or missing (they could get auto-deleted or prefixed with something, I honestly don't care), but if we can get the whole game recorded for our stats, it would be a really great thing! (Currently I do all of this manually every time a disconnect happens to me).

**Comment by mvordeme** [comment]
Could it be that this is partially working already? I had a few funny games where HDT started flashing halfway through the game and they were recorded twice. When I double-click them, only a list of drawn and played cards is displayed and not the replay viewer.

**Comment by culinko** [comment]
This is the bug related to jousting I think.

**Comment by garudajava** [comment]
Just had the same issue, I believe.  Was disconnected, and upon reconnecting to game, had lost all info from both decks.  Also, no result was included for deck statistics at the conclusion of the game.
