### ISSUE TITLE
heartharena build helper?

### ISSUE THREAD

**Issue by marcspc** [Epix37/Hearthstone-Deck-Tracker#946]
Hi, I know this isn't even remotelly close to any actual function of Hearthstone-Deck-Tracker, but could you implement a new function in order to OCR available cards when building the arena deck and automatically write the names on heartharena on a keypress or something like that?

Arenavalue works like this, but heartharena makes better decks.
Thanks for this great tool.

**Comment by rrwoods** [comment]
I was wondering about this as well.  Is there some way of determining which cards the arena is offering you, so that you could use a drafting assistant without having to manually type the cards?

I'd be willing to work on an extension to do such a thing (I *think* HearthArena has an API, and if not I'd be willing to open a dialogue with them about it as well), but I don't know if there's a way to get what we want.  The above poster mentioned ArenaValue using OCR to determine the cards it's offering you; how reliable is this?

**Comment by marcspc** [comment]
try arenavalue to find how reliable it is, it works 100% unless you hover the cards or something that affects the OCR, shame value calculation doesn't count with sinergies with previous cards

**Comment by Epix37** [comment]
I tried OCR in the past but did not have too much success with it. 
I'm sure it's possible though. Reading the name plus the manacost of the card should end up being pretty error resistant. I would guess that'w how arenavalue does it. 

The logs contain nothing about arena drafts and the only other ways I can think of for doing this would be TCP or memory. Neither of which are a good idea.

Having HearthArena integrated into thiss would be amazing.

**Comment by rrwoods** [comment]
I have grand visions for how HearthArena integration would look and function (automatic deck creation and naming, deck coverage overlays during drafting) and I'd be totally on top of writing an extension or contributing to the project directly -- IF we could find some way of figuring the picks without examining memory or traffic.

**Comment by marcspc** [comment]
I tried contacting arenavalue creator by email, will ask him to post here if he answers and is willing to help

**Comment by culinko** [comment]
It would be great if you could somehow record drafts with OCR and I would definitely try to draft with HearthArena if it will display all the values automatically (even though I never tried HearthArena before, I was always too lazy to input all the things manually). Also, we still need Arena entities (I updated #875 ).

**Comment by andburn** [comment]
I tried OCR on an extension I've been working on for HDT to automatically create a list of a users card collection(s) (*more on that another time*). Similar to @Epix37 I had little success with it. I think the problem is the text on the cards isn't straight, and also the text size varies depending on the length of the card name.

The most reliable way I've seen of recognizing cards is a PHash ([Perceptual Hash](http://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html)). I came across it on a [Twitch Bot]( https://github.com/wittenbe/Hearthstone-Image-Recognition) that uses it to recognize cards on stream, supposedly Trump uses/used it. It hasn't been updated in long time and its in C++, so I never bothered with. 

I had another look at it when I saw this thread and it turns out that [HearthstoneTracker](https://github.com/HearthstoneTracker/HearthstoneTracker) has an implementation of a pHash in C#. I've been playing around with his implementation using a simple console application and a small number of cards and it seems to work ok. Seeing that its Open Source shouldn't be any problem using it in HDT?. I'm working on getting all the card images from the web so I can create all the pHashes and do some proper testing. I'll report back soon :smile:

**Comment by culinko** [comment]
Great news! Also, I'm just wondering, would it be theoretically possible to track card pack openings with this method?

**Comment by andburn** [comment]
In theory, yes. If this method works as good as it seems (a big if at the moment). I've a feeling the gold cards would cause a problem though, because of the animations. Something to look at down the road maybe.

**Comment by marcspc** [comment]
thanks, let me know if I can help (beta tester)

**Comment by heartharena** [comment]
I felt I needed to register to let you guys know the HearthArena staff is preparing something in the same direction which we would like to be the primary way. It would be unfair to need respond to this topic and let many of your coding-hours go to waist.

**Comment by andburn** [comment]
Thanks for letting us know. I've put some time in already, but I learned stuff so its not wasted. Looking forward to see what you come up with :+1:

**Comment by marcspc** [comment]
really? I asked on their reddit and their answer was something like "don't be lazy"
http://www.reddit.com/r/HearthArena/comments/2yfcw8/auto_introducing_the_cards/

**Comment by rrwoods** [comment]
As was pointed out on that thread, you can only work on so much a time when you have so few developers.  When you asked the question before, HA was still very much in the phase of having the recommendations solidified -- the algorithm is the most important part, and if it isn't right then it's not doing its job.  (If the latest coop stream is any indication, the algorithm still has a lot of work to be done on it, but it's pretty solid.)

Now I get the impression the HA guys have a little more time to work on nice-to-haves.

**Comment by borick** [comment]
Hi, dev from hearthdrafter.com here - I have built am already WIP such a thing! I will be improving it over time, and would be happy to integrate systems if given the chance let me know :)

**Comment by Epix37** [comment]
Hey!
Website says 502, but yes I would love to! As a plugin or directly in the software how ever you prefer. Feel free to email me if you want to talk in more detail: epikz37@gmail.com

**Comment by borick** [comment]
thanks for the notice - it's up now

**Comment by borick** [comment]
Hey! Thank you so much for the notice. (I'm going to look into what went
wrong.)

Site should be up now. I love your software by the way! I'm actually
working on improving my reader... you've done some amazing things I would
love to use, but I have not yet chosen to open source my reader app...
I'm actually working on integrating Direct3DHook as next item :)
I really love the ability to read the cards off the deck screen, it's
amazing! Actually, Jeff from hearthstats told me about your site today :)

Let me know if you ever want to chat, or you have any questions or issues!!

Thanks again.
--Boris Sitsker

**Comment by Epix37** [comment]
And then there was this: https://github.com/rembound/Arena-Helper

**Comment by marcspc** [comment]
tested and compared with heartharena results, seems to work good, but 2/30 recomendations were very different from what heartharena, maybe I messed something since I was moving from a window to another and selected some card before it was "scanned" by your program.
