### ISSUE TITLE
Better Arena Stats Screen

### ISSUE THREAD

**Issue by shikaku2** [Epix37/Hearthstone-Deck-Tracker#948]
There should be a better stats specifically made for the Arena.  It doesn't have to try to keep track of the rewards (if you could grab it it would be cool though) but it should show things like the average win rate in general, average win rate for specific classes, common card picks, and more I can't think of off the top of my head.

**Comment by culinko** [comment]
Adding arena rewards is not really that difficult, but we still need Deck Tracker to capture Arena entities from within the log. Currently, it captures only the matches. As for common card picks, you can only track picked if you created an Arena deck yourself. Because the draft is not in the log, you would need to add some OCR (#946). I requested some arena stats myself, too (n.3 in #875). It's good that many other people are interested in Arena too:)

**Comment by Elitesparkle** [comment]
I think a table for deck, class and overall respectively would be fine.
The table should have:
- number of wins in the first column;
- classes in the first row;
- win rates in the cells;
- overall win rates in the last column;
- average win rates by class in the last row.

A graph would be really good.

**Comment by shikaku2** [comment]
I think a nice compromise for card grabbing in Arena is this: Arena decks don't change unless you have 3 losses or you retire.  You can most likely grab the deck by watching multiple playthroughs and resetting the deck at 3 losses.  Something like that, probably needs some kind of UI update though...

**Comment by riQQ** [comment]
This is mostly implemented now. Only draft statistics are missing, but some of the information is only available in the Arena Helper plugin.
