### ISSUE TITLE
how to hide warning messages

### ISSUE THREAD

**Issue by gendalv** [Epix37/Hearthstone-Deck-Tracker#983]
how do I hide that it didn't find cards in a deck or whatever (in the top left corner)? I only want it to display timer and secret's tooltips.

**Comment by gendalv** [comment]
i guess i just have to select tracker->use no deck

**Comment by Epix37** [comment]
Ah, so you are getting the warning because you are deliberately using a deck that does not contain the cards you are playing?

Not sure if removing the warning is the way to go (I would rather eventually fix bugs that cause it when not intended). Use the "no deck mode" might be the way to go in your case though.

**Comment by gendalv** [comment]
yes I'm mainly using it to display number of cards, fatigue damage and secrets
